### ISSUE TITLE
Styling output popden from categorical flood hazard

### ISSUE THREAD

**Issue by maning** [inasafe/inasafe#1111]
## Problem

As we are developing the IF for categorical hazard and popden (issue #1105 ) we are thinking about how to properly style the output raster. The output raster shows the popden (green-dark red gradient).  Obviously it doesn't show which areas are in what category of hazard (low, medium, high).  See output below:

![default_render](https://cloud.githubusercontent.com/assets/353700/3337780/faed62fe-f850-11e3-9199-45e60af1839b.png)

Visualizing both the density and hazard category provides better map interpretation.
## Solution

I experimented with QGIS blend modes by overlaying the output popden over the flood hazard.  See output below using the hardlight option:

![hardlight](https://cloud.githubusercontent.com/assets/353700/3337782/03b82004-f851-11e3-92a4-2126940613ed.png)

The output map IMHO looks better (but we need to explore more on the correct blend mode).
Other ways maybe, represent the color according to the hazard type (low,medium, high) and the intensity according to the popdensity.
## Further questions
- How do we add blend modes in the output raster style?
- Blend modes style is not visible in printed pdf output (using the default inasafe-portrait-a4 template) #1112 .

Of course other ideas are welcome.

CC
@dichapabe @assefay @timlinux

**Comment by timlinux** [comment]
@maning In InaSAFE 4 we are moving to showing only displaced population as a binary output.  And then we would show hazard zones over that.  I think for now we don't have priority to work on blend modes etc. in the future maybe it is something we could consider.  Since this issue has sat for a long time with no movement I would prefer to close it - we can re-open it again if you still need this behavior and want us to pursue it. Thanks, Tim
