### ISSUE TITLE
RFC : Network analysis

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#1670]
## Feature 
* Have a network analysis tool in InaSAFE
  * Dijkstra's algorithm to determin optimal routes for people to travel along from impacted areas to IDP camps (Internally Displaced Persons)
  * Use [the QGIS network analysis library](http://qgis.org/api/group__networkanalysis.html)

* [Uses cases](https://www.lucidchart.com/invitations/accept/c2cd97d5-f71b-441d-bb82-8b32adbce8a2)
![network analysis - use case](https://cloud.githubusercontent.com/assets/1609292/6962130/f175b178-d931-11e4-8cc0-dd176b981090.png)

Layers | Route from flood's edge to IDP
--- | ---
Flooded area | X
Roads : type | X
IDP, hospital | X

## Expected result
* A layer with only roads which are used by one of the route to go to the closest IDP/hospital. A new attribute will contain the IDP id so as to apply a style for each IDP catchment area.

[Nearest IDP](https://docs.google.com/drawings/d/1O7AAJ-i8j0VJ45Q5yHu3nDFxGrHeRDQcD2uGlY9lgqo/edit?usp=sharing)
![nearest idp](https://cloud.githubusercontent.com/assets/1609292/8202384/b4709fa2-14d9-11e5-8cf4-eb7bea09e4f7.png)

## Workflow
1. Get an IDP/hospital layer
  1. 3 ways : 
    1. Download some potential area from the OSM downloader (cf potential IDP below according a set of OSM tags)
    2.  Download IDP from the OSM downloader [cf osm key idp=*](http://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Tags/Humanitarian_Data_Model#Internally_Displaced_People_.28IDPs.29_camp_site)
    3.  Set the keywords for an existing layer with the wizard
  2. Identify IDP/hospitals which are dry

2. For each IDP (We assume that people are on the flood edge) : 
  1. compute dijkstra (less IDP than exits)
  2. save the list of couple (exit - cost)
  3. select the minimum cost route
  4. get the route
  5. assign idp id to all segments of the shortest route

3. For each exits : 
  1. check that an IDP is allocated

4. Find the limit on a flood edge where two exits have the some cost and assign the IDP id to these two new segments. See yellow circle on the schema above.

5. Apply a style on the new roads layer by IDP's id.

6. Get a report.

A manager can enable or disable an IDP if he wants to see the impact of an IDP (if it's full).

## Technical workflow

* The algorithm will use Dijkstra, provided by the network analysis library in qgis.
* The default cost is the length.
* It's possible to take care of the type of the road. But if we speak about type, we need to define default value for the cost for each type (eg speed limit) and allow the user to change them, isn't it ?
* It's possible to deal with oneway if a column is available. However, I don't think that oneway will change the result about catchment area. And do we care about oneway when a disaster happened ? :)

[Lucidchart](https://www.lucidchart.com/invitations/accept/8a6beb8b-5866-46d0-a05d-480541bf82ad)
![network analysis - new page](https://cloud.githubusercontent.com/assets/1609292/7018839/ca3f380a-dd09-11e4-9f88-67036e4b9c7f.png)

## OpenStreetMap : potential IDP
key | value
---- | ----
amenity | school
amenity | place_of_worship
building | public
leisure | sport_centre

## UI
* A wizard step by step to select the layers needed

## Gantt
[Lucid chart](https://www.lucidchart.com/invitations/accept/024717ad-1fec-41ef-a41d-f11783667602)
![gantt - gantt chart](https://cloud.githubusercontent.com/assets/1609292/6961705/e2c3c5e2-d92d-11e4-8a01-8fe43e8b536f.png)

## Further ideas
- Get some isochrones from IDP, using the only dry roads.
- According to a "people in building" layer and the capacity of each IDP, the algorithm should assign to each flooded building the closest IDP without putting to much people in the same IDP.
- Create Weigthed voronoi according to the capacity of the IDP : 
![voronoi_rfc](https://cloud.githubusercontent.com/assets/1609292/7023976/d2acd6de-dd39-11e4-8347-2a351e06a283.png)
  - However, voronoi doesn't care about a population layer
  - Voronoi draws polygons according to the position of a set of points. Even if an IDP has a bigger capacity, it may have a smaller area.
- Analyze the network : 
  - Compute connectivity
  - Detect strongly connected component
  - Detect edge which are critical in a case of flood
  - Detect some topological errors
  - [Detect where it might be possible to create a shortcut](https://docs.google.com/drawings/d/19OXIVTmEWVyDIKl7hHyujqACrNSREvVglB1rTope1TA/edit?usp=sharing)

## Existing work : [FLOOgin](https://github.com/D2KG/FLOOgin)
Another project based on InaSAFE : 
* However, it's working on an older version of InaSAFE API
* Routing is only available between two points avoiding a flooded area.

## CC 
@timlinux , @vdeparday , @Charlotte-Morgan 

## See also
* https://github.com/AIFDR/inasafe/issues/416

**Comment by Charlotte-Morgan** [comment]
hi @Gustry - in general this looks fine and addresses the milestone deliverable. 

I have no experience with this type of analysis but understand the concept and need for this capability.  I am aware of others running similar routing analysis manually for Contingency Plans in Indonesia and I am interested in getting their comments.

From me, I would like to look a little more closely at the data:
1. OSM buildings as IDP
* Great choice and if a filter can be applied to the downloader to identify building types that meet IDP requirements then that is good (see special filter used for people in buildings #1179). @iyan31 - can you please comment on the list of standard OSM building types that would be considered suitable as IDP from your experience?
2. Other sources of IDP. I would like you to consider other IDP data sources as these are regularly captured as capacity data by disaster managers and may well sit outside OSM. @iyan31 - do you have a sample dataset from Jakarta Flood or Bengawan Solo CP of IDP data sourced from somewhere other than OSM?
3. Will you also need run an analysis (not in diagram) to check that potential IDP are not flood affected?

2. OSM roads as routes
* Great choice and again, I think maybe a specific filter will be needed to identify roads suitable for routing. ie the current display types may not be a good field to use.
* Cost path - lets keep it simple and start with length & not consider speed limit or one way roads

3. Flood edge
* This is interesting & I understand why you use this - however it is not where the people will be. 
* boats are often used to get flood affected people to the flood edge. Could you use this analysis to determine where people should be 'landed" in order to get to a specific IDP if being evacuated by boat and considering that boats travel along flood affected roads.?? This is a sort of inverse analysis of roads inside the flood polygon @tim - I know, completely out of scope :)

4. OSM downloader vs selecting data from an existing dataset
* if this is being used in a disaster ... then maybe people will want to work with data they have already available & might not be able to use the downloader.  Can we 'post process' osm data that have already been downloaded for use in this tool? or look at working with filtered layers #1085 

# cc
Calling on others to comment on this RFC please. Especially if you have experience in IDP centres & connecting people and resources to those centres. How well does the proposed analysis reflect your experience and do you have any specific use cases to add to the discussion?
@vdeparday @iyan31 @adissadis @fredychandra @samnawi @assefay

**Comment by iyan31** [comment]
Hi @Gustry & @Charlotte-Morgan I agree that this feature looks promising. Few comments though:
* I would not suggest using idp:camp_type since this tag is already outdated, but potential IDP proposed above is really recommended
* For other source of IDP is a bit of difficult. In Jakarta flood, they only provide IDP camp name and address without coordinates. We try to add to map the location manually but it would take considerable amount of time. We do have sample dataset here: http://bit.ly/idp_jakarta_2014

**Comment by Gustry** [comment]
Hi @Charlotte-Morgan and @iyan31 

* OSM buildings as IDP
  * I would like to add a new item in the OSM downloader to provide buildings that meet IDP requirements.
  * In the use-case diagram, or in the workflow list, we will should be able to identify IDP which are not flood affected. A manager should also be able to unselect an IDP, even if it is dry, in case if this IDP is full.

* Flood edge
  * As a first step, we would like to focus on the route from flood edge to IDP.
  * If we would like to route from inside the flooded area, which start point should we use ?
    * People in buildings ?
    * Roads intersections inside ?
    * then [Dynamic segmentation ?](http://support.esri.com/en/knowledgebase/GISDictionary/term/dynamic%20segmentation)
  * At this step, for each exits, we can set the nearest IDP and the distance also. I've updated the schema above. If we look for the green IDP, we can notice that we should land people at approximately 600m (better than 1500m) from the IDP.

* OSM downloader vs selecting data from an existing dataset
  * As written, the manager should be able to use the keyword creator if he wants to use his own dataset. I think this analysis doesn't need a lot of settings about IDP, only a list of points.

**Comment by akbargumbira** [comment]
Hi All,

This is the IDP Camp for Flood 2014 registered to BNPB ArcGIS server: http://geoservice.bnpb.go.id:8399/arcgis/rest/services/Banjir_Jakarta_2014/Posko_Banjir_Jakarta_2014/MapServer

**Comment by Gustry** [comment]
I'm posting here a preview of my actual work.
Cost : It's using only the length, except along a flood edge, the length is multiplied by 100, in order to avoid walking on an edge.
About the question where people should be landed, the cost of each exits to an IDP is represented by a color from green to red.
I still have to put some colors on the flood edge.
![map](https://cloud.githubusercontent.com/assets/1609292/7449814/bbb5a42e-f23d-11e4-9b01-9527898fd8ed.png)

**Comment by timlinux** [comment]
Hi @akbargumbira 

> This is the IDP Camp for Flood 2014 registered to BNPB ArcGIS server: http://geoservice.bnpb.go.id:8399/arcgis/rest/services/Banjir_Jakarta_2014/Posko_Banjir_Jakarta_2014/MapServer

Do you know if they also publish WFS or GeoJSON? WMS isn't very useful for doing any analysis with.

Thanks!

**Comment by Gustry** [comment]
Edges are now splitted according to an IDP camp.
![map2](https://cloud.githubusercontent.com/assets/1609292/7808000/0f4055b8-0390-11e5-9216-6a640445f53f.jpg)
I will work soon on the template for the report, so comments are welcome about this proof of concept.

**Comment by timlinux** [comment]
Ah man that looks awesome...well done!

**Comment by Gustry** [comment]
I'm closing this.
This RFC is in the experimental branch and in https://github.com/inasafe/SafeRouting
