### ISSUE TITLE
We need feedback on IF from a new user

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1729]
I have asked @KathrynOwen to document some observations about impact functions from a new user perspective. She will use this ticket to provide feedback that may be relevant to the IF review.
# cc

@ismailsunni @akbargumbira @timlinux @lucernae

**Comment by timlinux** [comment]
Great - looking forward to your feedback @KathrynOwen !

**Comment by KathrynOwen** [comment]
Hello!

I get the feeling that I my feedback might be outdated now given that InaSAFE 3.0 is out and my feedback relates to version 2.2.3 so instead of creating seperate tickets for each issue, i will just dump all the feedback relating to issues i found with running analyses and the data here for now.

So here it goes. All the following feedback relates to using InaSAFE 2.2.3, QGIS 2.6.1, the data in the InaSAFEv2.0 zip downloaded from the website and the instructions from the Socialisation Training. Some of the feedback is far more important than others (e.g. the processing extent issue over the really insignificant grammar issues of missing question marks and capitalisation issues) but I will just dump it all here for now.

SOCIALISATION TRAINING DATA & EXERCISES:
General
•	When printing PDFs, if the landscape template is used, the map is cropped and the key/legend is also cropped off. 

•	When printing PDFs, nothing is displayed when the basic template is selected.

•	When printing a merged report PDF, the following error is encountered.
 
![image](https://cloud.githubusercontent.com/assets/10971278/6703051/c570b518-cd89-11e4-8fe3-390566fccc2b.png)

•	There is a missing question mark at the end of this error message:
 
![image](https://cloud.githubusercontent.com/assets/10971278/6703052/c9754142-cd89-11e4-9239-45e91f12fd08.png)

•	When printing a merged report PDF, after clicking yes to the above error message, the resulting report doesn’t appear to be merged and the map is cropped and the legend missing.

•	It appears that once a processing extent/analysis area is set for one project, it carries over to subsequent analyses on the same computer, even after restarting QGIS and saving a project with the extent cleared… is this an error within the InaSAFE plugin? i.e. extents not being cleared when a project is shut down?

‘Jakarta Flood on January 18th 2013’ data:
•	A ‘Be flooded (experimental)’ option appears in the Might field when this data is selected. Should this be removed?
 
![image](https://cloud.githubusercontent.com/assets/10971278/6703077/221a6a02-cd8a-11e4-8ce5-b4b03ad6c013.png)


‘A flood similar to the 2007 Jakarta event’ data:
•	Capitalise the keyword to People rather than people to be consistent with Buildings which is capitalised.
![image](https://cloud.githubusercontent.com/assets/10971278/6703081/2fb2c84e-cd8a-11e4-8171-dbf82089ce28.png)

•	The data is not aligned with the People data (Flood data = blue; beige = people; 45-65 People need evacuating = green; 0-1 people need evacuating = purple):
![image](https://cloud.githubusercontent.com/assets/10971278/6703098/55549780-cd8a-11e4-991e-49017bf248f5.png)
![image](https://cloud.githubusercontent.com/assets/10971278/6703100/59826a30-cd8a-11e4-9cb8-e7986d3d1092.png)

‘District’s of Jakarta’ data:
•	Remove the apostrophe in the keywords for the title to change it to ‘Districts of Jakarta’

‘Buildings’ data:
•	Some of the building data isn’t included in an analysis (i.e. it is not red, meaning inundated, or green, meaning not inundated)… and it doesn’t appear to be an analysis extent issue because it is not an exactly sharp line between what is and isn’t included in the analysis…

![image](https://cloud.githubusercontent.com/assets/10971278/6703109/7c5478c8-cd8a-11e4-8cde-956b6ee094f2.png)
![image](https://cloud.githubusercontent.com/assets/10971278/6703112/81b3f578-cd8a-11e4-8961-51d9fd0e2d45.png)

And it doesn’t appear to be due to the extent of the flood either as there are other buildings coming up as non-effected (green) outside of the flood extent layer:
![image](https://cloud.githubusercontent.com/assets/10971278/6703115/8ccb870a-cd8a-11e4-99d1-a6d1582924b6.png)
 
‘Merapi eruption/Volcanoes’ with ‘Buildings’ data:
•	When I run an analysis using the ‘Merapi eruption/Volcanoes’ with ‘Buildings’ data, I get the following key error, and thus no results:
 
![image](https://cloud.githubusercontent.com/assets/10971278/6703124/96ad1e8c-cd8a-11e4-82fe-419b1d41591f.png)

This occurs for both of the ‘Try it yourself’ exercises involving the Buildings exposure layer in the training manual:
![image](https://cloud.githubusercontent.com/assets/10971278/6703126/9b3f332c-cd8a-11e4-947a-a05c3c692e38.png)
 
‘an earthquake in Padang like in 2009’ with ‘People’ data:
•	When I run the analysis outlined in the Earthquake section of the ‘Other Hazards in InaSAFE’ page, the training manual says that I should get a memory usage warning…
![image](https://cloud.githubusercontent.com/assets/10971278/6703130/a8f38964-cd8a-11e4-9d53-51f29ce44c90.png)

 	But I don’t get a warning and QGIS becomes unresponsive and I need to end up closing it:
![image](https://cloud.githubusercontent.com/assets/10971278/6703132/b0440536-cd8a-11e4-8849-96e2d57cadb5.png)
 
	Perhaps the warning doesn’t come up on non-Apple computers?

•	Additionally, QGIS becomes unresponsive for analyses using each of the three People data sets – i.e. even with the coarsest resolution dataset which the manual says should be able to be processed without an error. 

When using the OpenStreetMap Downloader
•	When I try to use the OSM Downloader as outlined in the Tsunami>OpenStreetMap Downloader section of the ‘Other Hazards in InaSAFE’ page, the connection times out before any data can be downloaded. This occurs for large and small extents. 
![image](https://cloud.githubusercontent.com/assets/10971278/6703136/bd1ab98a-cd8a-11e4-8e25-fe46304a896b.png)

**Comment by NyakudyaA** [comment]
Most of the issues are not valid anymore. The grammar issues have been addressed by Reporting standards. Connection timeout is mainly internet connectivity and OSM server/by pass which fluctuates.

**Comment by timlinux** [comment]
Agreed thanks. Thanks for your feedback @KathrynOwen - I think you will find these issues are largely addressed in the upcoming version 4.
