### ISSUE TITLE
Translating the UI

### ISSUE THREAD

**Issue by severinmenard** [inasafe/inasafe#1757]
Would like to know wheter it is possible to translate the Inasafe UI in QGIS and if so, how to do it (I would do it into French). FYI I am a github basic user, I can edit files through it but I am not very comfortable with the forking process.

**Comment by mach0** [comment]
Hi! As InaSAFE is a plugin and not in the QGIS source code it is unfortunately not possible to translate it in QGIS (If I correctly understood what you mean). But it would not matter anyway because the translation of QGIS UI is done the same way as the InaSAFE translation is done .. In transifex. So there would be no difference anyway.

**Comment by severinmenard** [comment]
Sorry if I was not clear, my intention was not to translate it from QGIS, but to know if it was possible to get the plugin UI translated so that eg French Speaking people can have the Pluing UI in French. So my question would be: is the plugin potentially multilanguage and if so, where should I go to start the translation (using Transifex)?

**Comment by mach0** [comment]
Ah - ok.. well there is the inasafe_fr.ts in the i18n subfolder of inasafe. https://github.com/AIFDR/inasafe/tree/develop/i18n
You can translate this file with for e.g. Linguist (like in the former days of QGIS translation).
If you want you can just download it and translate it and send it to me and I commit it for you if you want to avoid forking and pull requests.
To summarize it: yes InaSAFE is multilingual and we should probably think about making it also easier in transifex. For now I hope it is ok for you to work on the downloaded ts file.
Thanks a lot!

**Comment by severinmenard** [comment]
Yes, no problem, I can manage a text file :)
Once done, it will automatically show up in the local language when this language is set in the QGIS general preferences?

**Comment by severinmenard** [comment]
In the text, there are a lot of <translation type="unfinished"></translation>
Should I change the type?
Other things to be modified?

**Comment by mach0** [comment]
Well, best way is to use a translation editor like qt-linguist (http://qt-apps.org/content/show.php/Qt+Linguist+Download?content=89360) or Kbabel (http://l10n.kde.org/tools/). It's more dangerous to directly edit the file with a text editor because if you forget something the file is damaged.
Hope this helps

**Comment by Gustry** [comment]
Hi Severin, I'm a french speaker too, so I can help you if you need.
It's easier to translate the file with QtLinguist.

**Comment by severinmenard** [comment]
Seems QtLinguist is only for Windows or MacOS. As I use Ubuntu, I will try
with Localize (formerly Kbabel)

On Tue, Mar 24, 2015 at 6:37 AM, Etienne Trimaille <notifications@github.com

**Comment by mach0** [comment]
@severinmenard linguist is surely available for Linux too
I have running it on debian (in package qt4-dev-tools or qttools5-dev-tools). Ubuntu might have similar package names. See here: http://lalescu.ro/liviu/fet/forum/index.php?topic=703.0
Hope this helps

**Comment by severinmenard** [comment]
Thanks for the tip, I installed QTLinguist without any problem indeed. Issue now is I cannot open the ts file. I have the msg below about an unexpected tag:

![qtlinguist_error_msg_inasafe_fr_ts](https://cloud.githubusercontent.com/assets/1291055/6995160/8419ea86-db25-11e4-9f10-cf479a8c460e.png)

**Comment by Gustry** [comment]
Did you start editing the file manually ?
The file works well on my laptop. You should probably download it again : 
https://raw.githubusercontent.com/AIFDR/inasafe/develop/i18n/inasafe_fr.ts

**Comment by mach0** [comment]
Hi!
I was just about to say the same. Yesterday I tested both files (from master and develop branch) and both loaded nicely without any errors in my linguist. Which version of linguist are you using?

**Comment by severinmenard** [comment]
Seems it was the file indeed, I downloaded a third time, from your link,
and it works now, thanks !

**Comment by akbargumbira** [comment]
Hi All, I think it's better for translators to translate InaSAFE UI in transifex, so that the translator don't need to install anything. There is some changes with the workflow on inasafe doc that affects the translation of the application in transifex.

@timlinux I can spare 2/3 hours of my time this week to set up a separate project in transifex for inasafe code if you want me to do it. This is a priority I think as people want to easily collaborate on this.

**Comment by akbargumbira** [comment]
Hi @severinmenard, instead of translating it to french in QtLinguist, can you make a transifex account and translate it there? https://www.transifex.com/projects/p/inasafe-apps/ 

There are some benefits using transifex:
- No need to install other applications. 
- There is glossary so you can define some terms and what the translation of those terms should be
- Some small features: you can see the last username who does the translations of a phrase, or suggestion of a phrase.
- You don't need to push the translations to github. Let the developers pull the changes from transifex, compile the translations, and push it to github (maybe once a week)

**Comment by severinmenard** [comment]
I already have a Transifex account and I used to it, basically I translated
part of the InaSAFE documentation into French with it.

I already started to translate through QT Linguist, so I make a pull
request with the file and continue with Transifex?

**Comment by akbargumbira** [comment]
Yes, that would be great. You can make a PR and I will merge it and update
it to Transifex. We will release InaSAFE 3.1 next week (20 April) and it
would be great to have some french translations included :)

**Comment by severinmenard** [comment]
I think I will focus first on the UI, then on the reports

**Comment by severinmenard** [comment]
What is the best way to provide my file into GitHub? I forked the
repository under my account, now I just click on the Edit (pen Button)
alongside  inasafe/i18n/inasafe_fr.ts and replace the original text with my
text or is there a way to just browse directly to my file?

**Comment by akbargumbira** [comment]
Hmm, I am not really sure about that since I think you edit the .ts file
from a not updated source. Can you email me the .ts file rather to
akbargumbira@gmail.com? I will sort it out and inform you afterward

**Comment by akbargumbira** [comment]
Hi @severinmenard, I have updated transifex and inasafe develop with your changes, it's working well
![french](https://cloud.githubusercontent.com/assets/992519/7089223/7cd27aa6-dfc4-11e4-901b-b8d6473f8891.png)

The transifex project for InaSAFE UI is here https://www.transifex.com/projects/p/inasafe-apps/

Thanks!

**Comment by severinmenard** [comment]
Great. I just sent the request to "join the French team"

**Comment by Gustry** [comment]
Thanks @akbargumbira

**Comment by severinmenard** [comment]
Actually right now all the 1212 strings are mixed and presented as a whole
in Transifex. Would it be possible to breakdown by category, as it was in
QT Linguist, so that I can organize better the translation, eg focusing
first on translating the UI then the report strings?

On Fri, Apr 10, 2015 at 2:36 PM, Etienne Trimaille <notifications@github.com

**Comment by severinmenard** [comment]
here is a screenshot from QT Linguist that shows the categories I am talking about: 
![inasafe_plugin_text_categories](https://cloud.githubusercontent.com/assets/1291055/7101501/074ef59c-e04c-11e4-8c0c-993aa1012e42.png)

**Comment by akbargumbira** [comment]
Hi Severin,

Yes that is a context given by the developers to the phrase (which usually
by the class name). I am not sure if in Transifex we can categorise based
on the context (I have no access to computer untill wednesday so I can't
really check it), but in each phrase there is an information box showing
the context, from which module that phrase is, etc.

If you are more comfortable with QtLinguist, please do it so. You can send
me the .ts file and I will merge it to Github and push it to Transifex. I
will be back to work on Wednesday.

Regards

**Comment by akbargumbira** [comment]
Please note that you better get the new .ts file again from github as I
updated it last night to reflect with the current source (
https://raw.githubusercontent.com/AIFDR/inasafe/develop/i18n/inasafe_fr.ts)

**Comment by severinmenard** [comment]
It is OK with Transifex, but could I have the rights to mark the text
strings as reviewed please?

**Comment by Gustry** [comment]
Hi @severinmenard, done, you are a reviewer now.

**Comment by severinmenard** [comment]
Basically a translation shows up only when a new version of the plugin is published, so it can take sometimes a few weeks after you translated a lot of text to get the results in the UI. Would it be possible to include significant improvements in translations as valuable reasons to recompile the plugin? If yes, what would be the best way to request it? Through an issue does not seem to be really straightforward.

**Comment by akbargumbira** [comment]
Hi Severin,

I think it's better for you to run the development plugin from the source.
You can ask the developers (cc Ismail) to guide you on that. They probably
pull and push the translations regularly, not just before the new version
gets published.

On Mon, Nov 2, 2015 at 8:32 PM, severinmenard <notifications@github.com>
wrote:

> Basically a translation shows up only when a new version of the plugin is
> published, so it can take sometimes a few weeks after you translated a lot
> of text to get the results in the UI. Would it be possible to include
> significant improvements in translations as valuable reasons to recompile
> the plugin? If yes, what would be the best way to request it? Through an
> issue does not seem to be really straightforward.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AIFDR/inasafe/issues/1757#issuecomment-153133476>.
>



-- 

*-------------------*

*Akbar Gumbira*
*Software Engineer*
*Geospatial, NLP, Data Mining, Machine Learning, Artificial Intelligence*

**Comment by lucernae** [comment]
Hi Severin,

@severinmenard we usually update translated text in the UI before plugin release because it is often that the text changes significantly during development phase. We generally don't want to translate while the text maybe changing multiple times. We usually declare a "string-freeze" period before release where we make sure no new text will be added to the code while we translate them (to make sure the effort is efficient).

As for your question about "Can significant translation update reason enough to recompile the plugin", I'm not sure about that. Maybe @ismailsunni or @timlinux can give a better insight. As far as I know, recompiling the plugin and publishing it to QGIS plugin repo needs some approval process, so it is desirable to publish periodically for bulk changes. But if you want to see the translation in the development version (by installing it into QGIS from this github repo codebase), I think it is possible for you to just ask us via issue to pull your translated text and then we can recompile the text in the UI for you. That way you can check the results in the UI by installing this github code to QGIS.

**Comment by ismailsunni** [comment]
Hi Severin

> Would it be possible to include significant improvements in translations as valuable reasons to recompile the plugin?

My answer, Yes, if it's really significant. We can release it as revision release (for example, 3.2.1 to 3.2.2). We can release this version without the bureaucracy approval (if @Charlotte-Morgan said ok, we can release it).
How? If you find that significant translation, just open an issue and tell where's problem, and the fixed (usually in transifex). After that, I will pull the translation from transifex, compile it, so that it comes out in the InaSAFE. Then, I will make a PR for it. If it's merged, we can release it.

If you want to see the translation in the InaSAFE (before it's released), you need to have dev environment in your local machine and do what @lucernae mentions in the previous comment. I can help you with that if you want.

Thanks :)

**Comment by Gustry** [comment]
I'm closing this issue. We are using transifex. If any problem, feel free to open a new ticket.
