### ISSUE TITLE
Population report issues

### ISSUE THREAD

**Issue by cchristelis** [inasafe/inasafe#1921]
# Problem

We are consolidating the reporting of the impact on population. It would improve the quality of our reports if they where not only consistent in form and presentation, but also in numbers and wording.
# Issues
- We have different ordering of the major elements in various IFs. These are impact summary (including breakdown where applicable), minimum needs, action checklist and notes.
- Terminology is inconsistent 'People' vs 'Population', 'affected' vs 'displaced' vs 'need evacuation' vs 'impacted'.
- Totals are rounded so the impacted per hazard zone can not always be added to total (70 high, 70 medium, 70 low, 200 total)
- Total numbers are different in the impact summary (total = 200) vs the post processors (total = 192)
- Some reports have no action checklist
- Rounding is indicated by a \* with a note in some reports and just applied without notes in others.
# Proposed solution

A recommendation should be made for each of these points and the report mixin should implement these. (#1765).

**Comment by cchristelis** [comment]
For the ordering issue I propose using:
1. impact summary
2. minimum needs
3. action checklist
4. notes

**Comment by akbargumbira** [comment]
# Rounding Problem
I just read  again the chat history in HipChat

"Akbar Gumbira	@christian for the implementation I think it would be better to handle that in the population mixin itself	5:18 PM
Akbar Gumbira	 so like I mentioned above, that rounding should be handled in 'presentation' layer	5:19 PM
 Delete	Akbar Gumbira	 IF could pass it to the mixin in un-rounded form	5:19 PM
Akbar Gumbira	 the report mixin will handle that rounding"

So, I think it would be better for rounding to be done in the mixin, not in the IF (IF should always give unrounded one) - though in some case that we and @timlinux found here on ITB we might want to do some rounding manipulation in the IF.

# Postprocessor and IF result are different
> Total numbers are different in the impact summary (total = 200) vs the post processors (total = 192)

It is because we pass unrounded number to postprocessors but not for impact summary. Like I said earlier, I think we should only round things in the 'presentation layer' and pass to others in unrounded form.

**Comment by timlinux** [comment]
I agree that rounding numbers only in the presentation layer would be the nicest approach. We should also indicate to users when numbers being displayed are rounded.

**Comment by timlinux** [comment]
In InaSAFE 4.0 numbers are rounded at the presentation layer. We also have standards proposals e.g. #2920 which cover these requirements more precisely. Closing this.
