### ISSUE TITLE
Tsunami Evacuation option - update

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2094]
# problem
the tsunami evacuation function invites users to enter 3 threshold values. However when it runs it only uses 1 threshold.

![image](https://cloud.githubusercontent.com/assets/5743135/8539891/c9d45308-24aa-11e5-8e8a-f12a94cb53b5.png)

# proposed solution
update the options to match the IF. 
I think the correct situation is one threshold value.

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
I checked in InaSAFE, it's actually running all threshold. See image below:
![inasafe - google chrome_046](https://cloud.githubusercontent.com/assets/1421861/8867616/f3b1f8f8-31f5-11e5-9da2-bd5e7d5c984f.png)

Red rectangle shows the breakdown of each threshold
Blue rectangle only shows the highest threshold.

So, I think the behavior is right.

**Comment by timlinux** [comment]
@samnawi can you please test this with QGIS 2.8.3?

**Comment by samnawi** [comment]
Ok @timlinux , I'll testing now

**Comment by samnawi** [comment]
@timlinux this is the result when I run it in Windows OS and using QGIS 2.8.3
![image](https://cloud.githubusercontent.com/assets/8871958/9246508/336921f2-41d6-11e5-9dff-1a32c4ab708c.png)

Actually, there is no detail breakdown data when I just use 1 threshold, 
but when I use 3 threshold, the detail breakdown data just show 2 level.

**Comment by ismailsunni** [comment]
hi @samnawi 

First image:
When we use only one threshold, we do not need the detailed breakdown, since we only have two interval. [0 to threshold] and [threshold to max]. Since we do not care about the first one, we do not show that. Meanwhile, the second interval has been shown in the upper part of the report.

Second image:
When we use three threshold, we will have 4 interval.
0 - first_threshold
first_threshold - second_threshold
second_threshold - third_threshold
third_threshold - max

We do not care about the first interval (we assume that if there is water that has depth less than the first threshold [lowest threshold], we assign it as not flooded).
We have shown the last interval in the upper part of the report (blue box).
So, we only have two remaining interval, and we put it in Detailed Breakdown (Red Box)

So, all behavior is still right.

Unless we want to change the behavior.

cc @Charlotte-Morgan @timlinux

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - agree the behaviour is ok. I think we should reconsider changing the behaviour but this can wait till we finish the review of all impact functions (Minions working on this now) & we can write a new tickets
FYI - Minions are @fredychandra @samnawi @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
behaviour should change as per new default thresholds proposed  for people, buildings and roads

**Comment by Charlotte-Morgan** [comment]
@samnawi  - can you please look at this with the tagged version of 3.3 and if its ok now we can close this ticket

**Comment by samnawi** [comment]
I've tried the IF, and I think the result id good.
![selection_091](https://cloud.githubusercontent.com/assets/8871958/13665157/8b5d265e-e6dd-11e5-9da2-2ea492a75cba.png)

@Charlotte-Morgan Just the question, what is the background so we decided 0.7 as the default?
I think in the real world, in any depth inundation from tsunami, I'm pretty sure (_it just my opinion - please correct if I wrong_) people in that location will doing evacuation. And as I know, the inundation in tsunami is different with flood. Because the tendency in the flood there is no stream, but in the tsunami, there is a stream in there (So, it more destructive than flood inundation).

Thank you.

**Comment by Charlotte-Morgan** [comment]
Professional advice from Pak Hamza - tsunami expert

**Comment by Charlotte-Morgan** [comment]
fixed in PR #2859
