### ISSUE TITLE
Switch to a chat system that does not require an invitation to join

### ISSUE THREAD

**Issue by vdeparday** [inasafe/inasafe#2114]
In order to grow the community faster, it would be great to switch to a platform that is open to everyone to join without requesting an invitation.
It looks like gitter is where things are going. We are trying for GeoNode and it seems very good. Do you want to start using it and transition there?

**Comment by timlinux** [comment]
We have been using gitter for QGIS and it is very nice and will act as a drop in replacement for HipChat (including dropping images into the chat which is my best feature of hipchat). I will be happy to switch and get rid of the overhead of managing users in HipChat.

I have set up a room here that we can use:

https://gitter.im/AIFDR/inasafe

It would be really nice to be able to embed it directly into http://inasafe.org so people can chat straight from the site. I will start to publicise the proposed switch and see if there are any complaints before shutting down any marketing for the hipchat channel.

@Charlotte-Morgan FYI too

**Comment by ismailsunni** [comment]
But gitter needs github's account. I am not sure the community has github account. If we talked about developer community, it will be good. But, for common people, I am not really sure.

**Comment by timlinux** [comment]
Update: discussed on hipchat [sic] - there were some reservations about hte fact that gitter needs you to sign up with GitHub first

**Comment by timlinux** [comment]
More update on this:

* I discussed with @Charlotte-Morgan today and she agreed to the change to Gitter
* Taking into account the various pros and cons, my feeling is that Gitter will be the best choice - users can self-register and in general we want interested users to sign up for GH accounts anyway so that they can file tickets
* Gitter does not 'lose' history in the chat, which is a concern for the WB folks

Thus I will move over the 'official' chat channel to gitter and send an announcement to the mailing list advising others to use that as the primary mechanism for communication in real time.

**Comment by ismailsunni** [comment]
Move to gitter for a while, and so far so good.
Join us in https://gitter.im/inasafe/inasafe
