### ISSUE TITLE
User docs need to be updated

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2291]
There are some user docs that need to be updated for the 3.2 release. 
Some of the material in the user docs is also duplicated in the socialisation training materials. We need to update one version and cross reference materials where possible.

Examples of docs needing update
http://inasafe.org/en/user-docs/toolbar.html
http://inasafe.org/en/user-docs/functionality.html
http://inasafe.org/en/user-docs/postprocessors.html
http://inasafe.org/en/user-docs/application-help/index.html

@timlinux - maybe you are already working on this :) it looks different today to what it did on Saturday.

@iyan31 - we should discuss cross referencing for training materials

**Comment by iyan31** [comment]
Let's discuss this on the meeting today

**Comment by timlinux** [comment]
Just a comment on this :

My intention is to gradually move all context help (which is currently pulled from user docs) content away from the user documentation and into in-code text and images so that it is translatable as part of the normal coding workflow and that we no longer need to have a browser popup to read this help. See the examples in OSM downloader and extent selector dialog when pressing help button.

For the end user documentation as posted to the web site, I agree that maintaining duplicate information across different parts of the docs is a headache. When all the context help is updated I was going to propose that we retire the user docs (first ensuring that the context help is rich enough to include all the retired info) and just rely on the Socialisation and Training manuals.

What do you think of this approach?

**Comment by Charlotte-Morgan** [comment]
+ 1 for context help in the software
We (Minions and HOT) just had a discussion about training materials; noted the duplication etc. We were hoping you will update docs but if not we will need to pull stuff into socialisation training and migrate as much as possible to context.

**Comment by timlinux** [comment]
We have our new shiny help system. I do think there is more we need to add e.g. toolbar descriptions - I hope to spend some more time on that next week and then we can hopefully close this.
