### ISSUE TITLE
Bug: Volcano point on buildings causes QGIS crash if all categories are < 1 km

### ISSUE THREAD

**Issue by cchristelis** [inasafe/inasafe#2306]
# Problem

When running the Volcano point on buildings IF, it goes into an infinite loop when running with small categories. 

# System

Tested on: 
Fedora 22, OS X 10
2.8.2

# Reproduce
 
- Add test layers
- Select options
- Remove all categories
- Add the categories: 0.9, 0.5 and 0.1
- Run IF

**Comment by samnawi** [comment]
@cchristelis I've tried to run it in my computer, and the result is fine although I run the all categories are < 1 km. 
![selection_208](https://cloud.githubusercontent.com/assets/8871958/9929167/3a2c71ca-5d55-11e5-971c-c03260b1eb05.png)

But, the problem is appear when I add small range like 0.1. I think the processing goes into an infinite loop when there is a small radius like 0.1.

PC Platform
Linux Ubuntu 14.04
QGIS 2.8.3
InaSAFE 3.2.0.dev-8357391

Thank you.

**Comment by ismailsunni** [comment]
Short and easiest solution would be giving error message to the user if they input less than 0.1 km. We can also add it to the parameter description. Moreover, in radius 0.1 km, there won't be any building or population.

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - can you please see if this is still a problem?

**Comment by ismailsunni** [comment]
I tried today, and all looks good now. I thingk @Gustry 's new method to generate the buffer fixes it.
<img width="392" alt="screen shot 2016-08-04 at 17 09 43" src="https://cloud.githubusercontent.com/assets/1421861/17398355/931f3c22-5a66-11e6-8e8b-f68f788addb8.png">
