### ISSUE TITLE
IFCW: Ensure the "non-matching keywords" table uses strings imported from definitions wherever possible

### ISSUE THREAD

**Issue by borysiasty** [inasafe/inasafe#2349]
See PR #2323. Also related to #2329.

**Comment by timlinux** [comment]
@borysiasty please see the helper method I wrote for keywords which you should be able to adapt or use:

https://github.com/AIFDR/inasafe/blob/develop/safe/utilities/keyword_io.py#L679

It might also be nice to use the message approach to construct the keywords so that the presentation in the wizard is analogous to the presentation of keywords in the dock. See show_generic_keywords method in https://github.com/AIFDR/inasafe/edit/develop/safe/gui/widgets/dock.py
