### ISSUE TITLE
to_html() got an unexpected keyword argument 'wrap_slash'

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2504]
When I add a layer, I often got this error message : 
![layer](https://cloud.githubusercontent.com/assets/1609292/11590434/8cee140e-9a90-11e5-9463-f832e7679bc0.png)

* QGIS 2.12
* InaSAFE develop

**Comment by timlinux** [comment]
Can you replicate this on a clean start of QGIS?

**Comment by borysiasty** [comment]
To replicate, please open the volcano_krb.shp test layer. While opening, it fails to display the layer metadata in the dock (for the same result the wizard test #2494 fails when it attempts to display the summary):

File "/home/borys/sources/inasafe/safe/messaging/item/cell.py", line 121, in to_html
    wrap_slash=self.wrap_slash))
TypeError: to_html() got an unexpected keyword argument 'wrap_slash'

The reason is nested tables in the keywords html representation. Cell.to_html() calls self.content.to_html() with `wrap_slash` keyword argument. The self.content may be instance of either safe.messaging.item.text.Text or safe.messaging.item.table.Table (for nested tables). The latter doesn't support the `wrap_slash` argument.

The easiest fix would be to add this argument to the safe.messaging.item.table.Table.to_html() method.

**Comment by Gustry** [comment]
Yes this error happens with ``volcano_krb.shp`` for instance, with a clean start of QGIS.
According to my unit test in pycharm, tests are failing according to this issue also.

Thanks @borysiasty to have a look on this issue.

**Comment by timlinux** [comment]
Thanks for the diagnostics @borysiasty and @Gustry  - I've made an alternative fix with PR #2508
