### ISSUE TITLE
Layer name change enforced when InaSafe not in use

### ISSUE THREAD

**Issue by jorgegil** [inasafe/inasafe#2521]
I have realised that InaSafe creates a layer.xml and layer.keywords file with a shape file to keep track of various things, including layer name changes done in the Layers panel.

This affects every layer added to a QGIS session, including newly created memory layers, even if the InaSafe toolbar and dock panel are closed. In this case, if a new memory layer is created with the first name, it automatically gets changed to the new name, no matter how many times it's added. This even overrides names set by Python plugins. Only retains changes done in the Python console.

Maybe it should not change layer names of layers not being used/created by InaSafe?

Or QGIS users must ensure they uncheck the InaSafe plug-in if they do not intend to use it, to avoid it taking control of their layer names.

Thanks,
Jorge

**Comment by ismailsunni** [comment]
Hi @jorgegil 
Thans for your question.

In InaSAFE, you can disable this feature (replacing layer name with its title) from InaSAFE Options. See image below:
<img width="1290" alt="screen shot 2015-12-21 at 7 32 58 am" src="https://cloud.githubusercontent.com/assets/1421861/11921162/9cfd7916-a7b5-11e5-9126-92034b34ad00.png">

> Maybe it should not change layer names of layers not being used/created by InaSafe?

I don't think we can separate which layer are used by InaSAFE or not, since InaSAFE uses all loaded layers.

**Comment by jorgegil** [comment]
Hi @ismailsunni 
Thanks! That setting in InaSAFE is the answer that I needed.
