### ISSUE TITLE
Flood IF Analysis Layer Result did not Match with Hazard and Exposure Data [bug]

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#2529]
# Problem
Flood IF Analysis Layer Result did not Match with Hazard and Exposure Data

# Detail 
I try to run flood IF using flood Jakarta (vector) and Java Population (raster). The result generally shows good result but when I zoom in to certain area some layer is missing. There is a hole between flood layer and the result layer. It should be at least be classified in analysis layer and overlap with the flood layer but unfortunately it is empty.

# ScreenShoot
![output layer flood_population2](https://cloud.githubusercontent.com/assets/2534179/11947246/e0e6450e-a896-11e5-8c4d-69572e50a827.PNG)

![output layer flood_population](https://cloud.githubusercontent.com/assets/2534179/11947250/e665a63c-a896-11e5-8466-f0def87839d8.PNG)

# Platform
Windows 8.1 64 Bit
RAM 4 GB
QGIS 2.8.4 Wien
InaSAFE 3.2.5 dev-master

# Data
Hazard : Jakarta_Flood_18113__WGS84.shp (Vector)

Exposure : 
*Java_Population_WGS84.tiff (Raster)

Agregation : Jakarta_District_Boundary.shp	

Cc : @timlinux @ismailsunni @samnawi

**Comment by samnawi** [comment]
I think it's because the symbology. If we look at the picture in the bottom, the hole in the result has a value < 1. 
![selection_004](https://cloud.githubusercontent.com/assets/8871958/12033306/1a9c1086-ae54-11e5-9cf2-5e784209f0a6.png)

When I try to change the symbology, the hole area filled by color also.
![selection_005](https://cloud.githubusercontent.com/assets/8871958/12033321/4b47fcea-ae54-11e5-963f-ed9ac4d6b39a.png)

# Problem
In the symbology, value 0 - 1 will represented with white color, but in the display the value < 1 represented by transparent color.

**Comment by ismailsunni** [comment]
@samnawi do you have a suggestion for a better symbology?

**Comment by samnawi** [comment]
@ismailsunni I just want to make sure if the symbology in the legend is white, there should be no hole / transparent symbol in the map.

**Comment by samnawi** [comment]
@ismailsunni has been created the PR to solve this problem.

@harrymahar From your perspective, what are your proposed to solve it?
@Charlotte-Morgan In this ticket, I think we get the problem about the value 0 < x <=1 that displayed with transparent color, so it become a hole in affected area. From your perspective, how should we do with this value?

**Comment by Charlotte-Morgan** [comment]
without looking at the data, here are some thoughts:
* any output cells greater than 0 (ie contain affected people) should be counted and symbolised so that they show up on the map. 
* all 0 or no data cells should not be symbolised - this area should be 'transparent' so that underlying layers are visible

**Comment by Charlotte-Morgan** [comment]
as discussed with @samnawi 
we need to exclude 0 values. The easiest way to do this is to tell the display that 0 values should be treated like 'no data'

the impact layer results look like this:
![image](https://cloud.githubusercontent.com/assets/5743135/12288951/10a4c100-ba0b-11e5-9fd7-f082facc9efe.png)

however - we spotted another issue, the labels on the affected population should be expressed as ranges - eg like this:
![image](https://cloud.githubusercontent.com/assets/5743135/12289008/727dbf8a-ba0b-11e5-8ff3-a915f1e88079.png)

@samnawi  - please write a new ticket for the default label style issue found above :)

**Comment by Charlotte-Morgan** [comment]
here is where to set no data on the transparency tab - i think you can remove the transparency setting once 0 is assigned to no data. 

![image](https://cloud.githubusercontent.com/assets/5743135/12289364/b7a30af0-ba0d-11e5-800c-fa5d2d47952a.png)

Please note this will only be relevant to population raster results where the null values were treated as 0 - check notes on IF to confirm
