### ISSUE TITLE
All Population be Affected in Flood IF Result [Bug]

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#2530]
# Problem
No Population be affected in Flood IF result

# Detail 
I try to run flood IF using flood Jakarta (vector) and Java Population (raster). The result shows number of population affected, people need evacuation and unaffected population. However, there is strange result where number of unaffected population is zero. It means, all people in Jakarta affected by flood eventhough the floodprone only happened in certain area.

# ScreenShoot
![unaffected population](https://cloud.githubusercontent.com/assets/2534179/11947670/0b5c1178-a89d-11e5-892e-4ea5bac85642.PNG)

# Platform
Windows 8.1 64 Bit
RAM 4 GB
QGIS 2.8.4 Wien
InaSAFE 3.2.5 dev-master

# Data
Hazard : Jakarta_Flood_18113__WGS84.shp (Vector)

Exposure : 
*Java_Population_WGS84.tiff (Raster)

Agregation : Jakarta_District_Boundary.shp	

Cc : @timlinux @ismailsunni @samnawi

**Comment by samnawi** [comment]
Hi @harrymahar I get this problem too. Either in WIndows 7 64 Bit and Ubuntu 14.04. Using QGIS 2.8.4 and 2.12.1.

![image](https://cloud.githubusercontent.com/assets/8871958/12031344/6684010a-ae3d-11e5-8ca2-724ed5c5e26c.png)

In the picture above, when I try to doing zonal statistics process using flood polygon as vector layer zone, generate the number of population 1,120,024. If the number is rounded up 1,000, similar with total affected population 1,121,000. It means that the IF just calculate people in the flood polygon area, whereas there is raster population data inside the analysis area, but outside the flood polygon.

**Comment by adissadis** [comment]
@samnawi @ismailsunni i think this will make people confused reading the result. People will think all the people is affected by flood and there is 0 people unaffected. While there are people who not in flooded area but the result counted as 0 people unaffected.

In my opinion, i think we better to remove information "Unaffected Population" for this IF to avoid this misunderstanding.

**Comment by ismailsunni** [comment]
@adissadis can you try my PR for this ticket above? I merely remove the unaffected population from the impact report.

**Comment by adissadis** [comment]
@ismailsunni  Its still appear in impact report:
![image](https://cloud.githubusercontent.com/assets/2520159/12256320/02d6f7e6-b92f-11e5-9a34-01e1cfe2f03e.png)

**Comment by ismailsunni** [comment]
@adissadis did you checkout my PR? Because I haven't merged it to develop branch.

**Comment by samnawi** [comment]
@adissadis and @ismailsunni if we want to remove the unaffected information, we must remove in the other IF also. It's about consistency. 

If we look in https://github.com/inasafe/inasafe/issues/2384, I proposed to appear the unaffected value is because we also show the total of exposure data.

Indeed, usually the user want to know the affected for the first. 
But for the other reason, sometimes the user want to know the unaffected, like to compare the percentage, etc.
How about your perspective @fredychandra ?

I think if we want to discuss about remove the unaffected information, maybe we can create new ticket.
The issue in this ticket I think is about unaffected data that not calculated.

Thank you.

**Comment by adissadis** [comment]
@ismailsunni i already check your PR and its worked

@samnawi if we don't want remove unaffected information then we need to provide information/note below 'unaffected people', maybe put note like *this unaffected population come from population inside the vector area*

If we don't put like that, maybe InaSAFE need calculate total number population inside the analysis area and then for unaffected people is come from *total population - affected population*

**Comment by samnawi** [comment]
@adissadis yeah... I agree with you. Because in this version, for the population IF, we have an information in the note about the total population in analysis area. Maybe we can add the information that you propose to make it more clearly, not make the ambiguous.

For the other exposure data, I think we also must do that.

**Comment by adissadis** [comment]
I'm sorry i'm little out off topic here. Just want to give some information. If you look at the other IF (Volcano vector with population raster data), it succeeded count people outside the hazard area. 
![image](https://cloud.githubusercontent.com/assets/2520159/12288232/e671483c-ba04-11e5-96ac-09ef3b500c6b.png)
Maybe you can replicate some of the code from there @ismailsunni

**Comment by ismailsunni** [comment]
Thanks @adissadis I will check it out, and see if we can do it in this IF also.

**Comment by ismailsunni** [comment]
@adissadis Thanks. It really helps. There is no code to count the unaffected in the IF before. Added in my above PR. Please review.

**Comment by ismailsunni** [comment]
Fix in #2581
