### ISSUE TITLE
[Realtime] Location / Placenames for EQ realtime

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2589]
This afternoon, I've a quickchat with Ibu Dian from Pusdatinmas BNPB. 
This is the conclution for our conversation :
- **For location of epicentrum**
  She gives the suggestion to use the information accordingly with BMKG.
  Maybe we can extract the information from this link http://data.bmkg.go.id/gempaterkini.xml
  ![image](https://cloud.githubusercontent.com/assets/8871958/12477382/cd1f3f02-c061-11e5-89a8-f3faf387e3a4.png)
- **For the nearby location**
  They (as a user) usually want to know the popular city like the capital of district.
- **Placenames with population data**
  They don't have any data of this.
  As the discussion with @Charlotte-Morgan. I'll try to use the capital of district in our database, and calculate the population in that town based on the percentage of population in rural and urban based on the data from BPS (population census 2010). Then try to compare it with the actual data or with the data from the other agency (if they have).

Thank you.
# CC

@timlinux @lucernae @fredychandra

**Comment by Charlotte-Morgan** [comment]
thank you @samnawi - this is a good approach.
@lucernae - are you able to automatically real from the *.xml file to report the same place name as BMKG?

**Comment by lucernae** [comment]
- For location of the epicentrum
  @Charlotte-Morgan @samnawi I can extract the place name of earthquake epicentrum from BMKG's grid.xml file. But they usually doesn't have any standard. Sometimes they uses city name, sometimes province name. For example here we have "Malut", and in the other grid file we have "Sumatra Barat". The idea is to put these names as "Location Description" field in the realtime earthquake table (in the bottom of the map. However, I'm not sure what is best, just follow BMKG's grid.xml files, or using our most affected place name? What do you think about this?
<img width="1149" alt="screen shot 2016-01-25 at 02 31 40" src="https://cloud.githubusercontent.com/assets/831865/12538424/d77ef076-c30b-11e5-8314-004728f4929c.png">

- For the nearby location
  This is already covered in the PDF report, right? Or do we need to put it also in the web table like above?

- Placenames with population data
  @samnawi you can give me data if you already compiled it. Preferably as vector layer format (shp). But I can also work with csv format with the place name as the reference name.

**Comment by samnawi** [comment]
@lucernae 
* For location of the epicentre
Maybe we can show it (the result) to BNPB, and see the feedback. How about you @Charlotte-Morgan ?
I think maybe we can use the current placename - geonames or the other (that we agree), but use the near location, not the biggest population as the location description like in this picture
![image](https://cloud.githubusercontent.com/assets/8871958/12548933/4e8acdd6-c38c-11e5-8931-ab87384ae9e0.png)
  
* Nearby location
I mean that they (the user) prefer to know the location just for the popular city (for early information), not very detail for example up to village level --> it influences what will we use in the third point.

* Placename with population data
Yeah @lucernae It's still on progress. I try to do some effort with BPS data and ask my colleague in Statistical agency, also the other agency about the data, but apparently they don't have the data that. So, I still try to do some effort with the BPS data.

**Comment by samnawi** [comment]
Hi @lucernae 

Please check your email, I sent you a link to download the placenames to support the EQ realtime.
Or, you can also download in [here](https://www.dropbox.com/sh/ibhodjntetcfcg1/AABAtobVTWZ3sxeTOD0rPVLpa?dl=0)

@Charlotte-Morgan it just for testing or we can use it with some disclaimer : 
1. The data source --> 2010 Population Census (499 district).
2. Use urban data from 2010 population census for each district as the assumption to represent the population at the capital of district.
3. The district that don't have urban population data, we use location approach by subdistrict or village name which similar with the capital name.

Thank you.

**Comment by lucernae** [comment]
@Charlotte-Morgan @timlinux @samnawi I've seen the data source. It seems we need to refactor a lot of code to be able to use the data of vector population. I'm trying to develop it so we can have these two methods running at the same time to compare it for now.

**Comment by Charlotte-Morgan** [comment]
@lucernae - i think you may misunderstand the use of the population data supplied. Lets discuss

**Comment by Charlotte-Morgan** [comment]
hi @lucernae - i have checked with @samnawi and this is the intention.
In EQ realtime - If i am not mistaken, there are 2 calculations. 
1. raster on raster with the eq IF to calculate the people affected. this uses shake map and world pop and generates the people affected results by MMI. 
2. places affected and the number of people in those places. this uses Geonames and generates the table of place names.

The problems:
* place names from Geonames are not the same as reported by other organisations
* the population attached to placenames is different to the population generated by worldpop analysis - we have conflicting information for the users.

# Action
How EQ Realtime will work with the new data provided by DMI.
1. stays the same - no change
2. a)  we would like you to stop using Geonames for the placenames analysis and start using the point data we supplied. The point data are the district capitals and have urban population for the district attached. 
2. b) In some cases the district capitals are missing or no urban population was quoted. In this case we would like you to use the polygon data. The polygon data are district boundaries and contain the total population for the district.

If the metadata supplied with the data do not explain this, please let @samnawi know so that he can supply better metadata.

Action 1 is no change. 
Action 2a should be straight forward

# expected outcome
After you implement action 2a - I would expect the place names to match other agencies terminology and that the population for places to be more similar to the affected population from worldpop.

Action 2b - should wait for feedback on the first change to see if it is needed. We may need to think how you can flip from point to poly data or if we should always work with poly data if the populations are still not similar.

There should be no changes to the IF supplied by Hadi and Hyeuk.
I hope this is clearer now. Obviously some metadata and disclaimer / source statements will need updating too.

# cc
@timlinux @easmetz

**Comment by lucernae** [comment]
Ok, It is a lot clear now. I should just replace the geonames. I think it would not need a lot of refactor.

Another follow up questions, if you take a look at the current realtime.inasafe.org, we already uses Location Description provided in the shake grid.xml of BMKG. But, if we compare it with this one:
[BMKG Recent Quake > 5.0](http://www.bmkg.go.id/BMKG_Pusat/Gempabumi_-_Tsunami/Gempabumi/Gempabumi_Terkini.bmkg), it still shows different place name.
Also this site : [BMKG Felt quakes](http://www.bmkg.go.id/BMKG_Pusat/Gempabumi_-_Tsunami/Gempabumi/Gempabumi_Dirasakan.bmkg) has a different place name format. There is a number there like ```II-III	AcehJaya```. I don't know where does II-III Roman number came from.
So, does the current Location Description is ok to use?

**Comment by samnawi** [comment]
@lucernae Maybe tomorrow I can help to check it with Ibu Dian. Because one of the proposed from Ibu Dian is the placenames should refers to BMKG.

**Comment by samnawi** [comment]
@lucernae I just have a chat with Ibu Dian, and discuss about the location description. I explains about the difference from 3 sources that you mean (shake grid, recent quake, and felt quake). She will follow up it to people from BMKG, because of the difference placenames and format from 3 sources.

Thank you.

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
