### ISSUE TITLE
bug:OSM downloader timing out

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2599]
# problem

The OSM downloader has been timing out for me. I have tried on my GA computer and my standalone laptop. I have tried different sized areas, down to a quarter of the size of the highlighted area in the attached picture.

# proposed solution

make it happy
try running it on a computer that is not connected to GA internet

cc

@Charlotte-Morgan 
![osm_downloader](https://cloud.githubusercontent.com/assets/16660099/12709871/5da7f62c-c904-11e5-94b3-83deb812d439.PNG)

**Comment by Charlotte-Morgan** [comment]
Hi @samnawi - can you please take a look at this and see if you can replicate or if its a special GA issue. @easmetz - can you please confirm that you also tried on your GA wired connection.

BTW Iwan - Libby is the new GA spatial support person for our project. Iwan is the GIS officer based in Jakarta.

**Comment by easmetz** [comment]
@Charlotte-Morgan I can confirm I tried on both the GA wired connection and the GA wifi.

**Comment by ismailsunni** [comment]
I tried it using my internet, it's still working properly.
Hi @easmetz, perhaps you can try to do it by using non-GA connection (e.g. tethering from mobile phone)

**Comment by samnawi** [comment]
Hi @easmetz 

Hi @ismailsunni I've tried in both of my machine (Ubuntu 14.01 and Windows 7), and it's work. But after the download data has been finished, I got the notification about network timed out.
![selection_072](https://cloud.githubusercontent.com/assets/8871958/12713343/964e0736-c900-11e5-82b2-191d3d963b18.png)

It's occured in Ubuntu and Windows machine, also in QGIS 2.8.6 and 2.12.3.
But, when I tried to setting the parameter in _Settings - Options - Network_  at _Timeout for network requests (nm)_ from 60000 to 6000000, there is no notification about network time out again after the download data has finished.
![selection_071](https://cloud.githubusercontent.com/assets/8871958/12713186/d8c9242a-c8ff-11e5-88d5-7d1f12046838.png)

Is the problem was related to this setting?

**Comment by Charlotte-Morgan** [comment]
@samnawi - good point. Thanks for checking this and your suggestion. @easmetz - you may want to see if the data downloaded correctly despite the error message and check out the time out settings.

**Comment by Gustry** [comment]
@samnawi This is a known issue #2588. I also have this message in my log panel, but also in QGIS GUI.
But if I understood the difference, @easmetz didn't get the data loaded in QGIS, right ? This message box stopped the download ?

**Comment by timlinux** [comment]
@easmetz also is QGIS configured to use your proxy nicely too? @easmetz great to have your bug reports by the way!

**Comment by easmetz** [comment]
@samnawi @Gustry @Charlotte-Morgan @timlinux @ismailsunni 
Thanks for the tips everyone!

I tried a bunch of different approaches today and it ended up working but it is not clear why. To clarify, before trying these approaches no OSM information downloaded into the relevant directories when the timeout message appeared (i.e. the message box stopped the download as @Gustry said).

My method:

1) First I changed my _Timeout for network requests (ms)_ from the default 60000 to 6000000 like @samnawi suggested and it didn't make a difference, I still got the same Timeout message. I kept the timeout length at 6000000 for the rest of the steps in this comment.

2) Then I configured QGIS to use my proxy and the OSM data downloaded and I got no error message.

3) Just to make sure it was the proxy causing the problem, I unchecked "Use proxy for web access", ran it again and it downloaded with no errors.

So the problem is solved, but I'm not sure exactly what triggered it to work, as the settings for when I ran it in step 3 were identical to the settings when I ran it in step 1.

@timlinux thanks. It's good to be working with you all!

**Comment by Charlotte-Morgan** [comment]
hi @easmetz - glad its working.  Not sure if 3 above is explained by caching, but I would recommend keeping your proxy settings current and this may mean updating every time you change your GA password. Anyway, welcome to tickets - this is a great first ticket.  If the issue is resolve you can close the ticket.
