### ISSUE TITLE
InaSAFE Realtime EQ: Failed to process non intersected hazard and exposure

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2652]
### Problem

- Correct clipped Exposure was failed to be produced when the hazard doesn't intersect current population raster (outside Indonesian boundary)
- ITB Fatality IF failed to process empty exposure (where hazard and exposure is not intersected and contains NaN value).

### Expected Behaviour

- Provides a bigger/wider population raster so BMKG grid.xml is always inside our population raster
- Provides default classes in case it doesn't found minimum class. See here: https://github.com/inasafe/inasafe/blob/develop/safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py#L360
- We should always make InaSAFE EQ exit gracefully in case the error is expected. Otherwise, always try to process it again.

**Comment by samnawi** [comment]
@lucernae So, the problem is because the epicenter in the middle of the ocean?
The shakemap is not intersecting with population data, because there is no population in there.
But, if I see the latest aftershock, the location is farther than the first earthquake (that not appear in the realtime)

My question :
1. How wide the coverage of BMKG shakemap? Is it different from one EQ to the other?
2. About the exposure data, should we prepare the population data with 0 (zero) value at the ocean, not just NULL?

**Comment by lucernae** [comment]
Yes, after looking at the latest shakemap it appears to be much farther. I'm not sure then. Maybe the problem actually in the clipper. I should take a look then.

**Comment by timlinux** [comment]
@lucernae Can you give an update on this? We should treat it as high priority please.

**Comment by lucernae** [comment]
I found the problem! I misunderstood some numpy functions. So it appears all value becomes NaN, because it was being added by NaN. So, we should filter NaN first and replace it with 0.

**Comment by samnawi** [comment]
OK @lucernae. 
It sounds good.
