### ISSUE TITLE
Realtime EQ contour smoothing

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2662]
# problem

InaSAFE EQ realtime needs to have its contours smoothed for display. However, the number of people exposed to different shaking levels should be estimated from the raw (not smoothed) data.

e.g.

map-raw
![image](https://cloud.githubusercontent.com/assets/16660099/13627330/c2f0b664-e61d-11e5-8e82-da0052540f4e.png)

map-smooth
![image](https://cloud.githubusercontent.com/assets/16660099/13627333/cd7a87ae-e61d-11e5-8ef5-ef646a181e7e.png)

map
![image](https://cloud.githubusercontent.com/assets/16660099/13627314/b11547f2-e61d-11e5-826d-a9b95f76cfea.png)
# proposed solution

For smoothing, Hadi used spatial convolution of intensity matrix with a smoothing kernel to filter out the high frequency part of the contours. In MATLAB you can do this by using “conv2” function. 
# cc

@Charlotte-Morgan @timlinux @hadighasemi

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz - thanks for writing this ticket.
Can you please ask Hadi to send his code that he has available?

# cc 
@lucernae - I think this one is for you

**Comment by easmetz** [comment]
@hadighasemi would like a very jaggy contour to be provided as an example for him to write code for. (he has misplaced his original code.)

also he would like to know if python or GMT is preffered.

**Comment by Charlotte-Morgan** [comment]
hi @samnawi - please find a good example of realtime eq reports with jagged contours. Then get the shape files and share with hadi please. 
@hadighasemi - please supply something in python - thansk

**Comment by Charlotte-Morgan** [comment]
#1201 - this has been around for a while

**Comment by Charlotte-Morgan** [comment]
see #1201

**Comment by timlinux** [comment]
@lucernae We could maybe use this approach:

http://stackoverflow.com/a/33125541/3849375

We would need to convert the line vertices into arrays and back again to a geometry. At the time of writing the realtime there was no handy smoothing function in QGIS. we since do have some so I would suggest first trying with the QGIS line generalisation API and see if you can find a useful approach there. If not revert to doing raw geometry unpacking, smoothing and then reformulating as a line geometry. Maybe this is something we can recruit @Gustry or @wonder-sk to help with - adding it to QGIS as a core function would be nice.

**Comment by timlinux** [comment]
Note that it is not really feasible to use the example in the stackoverlow link above as it uses scipy which is not guaranteed to be installed and we can't easily bundle it.

**Comment by timlinux** [comment]
We could also look at the code in this plugin: https://plugins.qgis.org/plugins/generalizer/

**Comment by timlinux** [comment]
This is what the Indonesian disclaimer currently looks like:

![screen shot 2016-04-21 at 15 17 32](https://cloud.githubusercontent.com/assets/178003/14710081/42b11196-07d4-11e6-96c6-152027b7253e.png)

There was previously a problem with the text being truncated, but this has since been fixed. Could you confirm if this text needs to be changed?

**Comment by wonder-sk** [comment]
If I understand correctly, the raw EQ data are in raster that is later converted to vector contours.

If that is correct - here are two simple approaches to make the contours smoother:
- simply downscale the raster to a lower resolution with GDAL and afterwards calculate contours; or
- add blur to the original raster by using GDAL virtual raster (and calculate contours on that virtual raster) - see http://gis.stackexchange.com/questions/20196/how-to-convert-geotiff-to-grayscale-and-add-gaussian-blur

It seems easier to remove the high frequencies from the raster by resizing/blurring rather than applying some generalization of vectors afterwards (that may also introduce unwanted artifacts).

**Comment by timlinux** [comment]
We could also look at using Visvalingam simplification (which preserves topology). @wonder-sk 's approach also sounds like it is worth trying. Here are some chat transcripts about simplification that might be interesting:


```
Tim Sutton @timlinux Jun 10 13:34
@Charlotte-Morgan Since it is friday afternoon for you, I leave you with this GIS geek thought: What if we used Visvalingam simplification to simplify features extracted from raster-> vector conversions like shake contours and flood/tsunami zones: https://github.com/mbloch/mapshaper/wiki/Simplification-Tips
Here are some little examples I made with the ash plume dataset from Adele for an example:
 
 
@lucernae you should probably check that out too
adn @Gustry
You can test bed it here: http://www.mapshaper.org
Just drop a .shp file in there (no need for the dbf and shx)
It seems it preserves topology too

Etienne Trimaille @Gustry Jun 10 13:40
This tool is very convenient

Tim Sutton @timlinux Jun 10 13:54
Here is an example based on the ambon data
 
Above unsimplified
 
below simplified using weighted alg
I think I used like 7.5% threshold
@Gustry Just protyping here I made a simple workflow to generalse the ambon data to polygons (without the Visvalingam simplicfication at this stage):
 (0 * ("Tsunami 15m area@1" <= 0)) + (1 * ("Tsunami 15m area@1" > 0 and "Tsunami 15m area@1" < 1)) + (2 * ("Tsunami 15m area@1" >= 1 and "Tsunami 15m area@1" < 2)) +
(3 * ("Tsunami 15m area@1" > 2))

Then polygonise with GDAL:

gdal_polygonize.py /Users/timlinux/gisdata/InaSAFETsunami/Ambon_Tsunami_Reclassified.tif -f "ESRI Shapefile" /Users/timlinux/gisdata/InaSAFETsunami/Ambon_Tsunami_Reclassified.shp Ambon_Tsunami_Reclassified haz_level
Both jobs run very quickly
I just need to find the landcover data that I can test with an exposure layer

Etienne Trimaille @Gustry Jun 10 13:58
but you use the online service for the simplification ?

Tim Sutton @timlinux Jun 10 14:01
I think simplification we can do in QGIS 2.16 so I am not proposing to do it now
qgis/QGIS#2900
See that PR @Gustry
mapshaper is a FOSS javascript lib
so we could in theory do it already client side using that

```

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
