### ISSUE TITLE
We need to move the PDF generation to the IF

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2670]
Currently the PDF is generated in the dock or in realtime's logic. We need to move all this logic to the IF base class.

**Comment by timlinux** [comment]
The method should take optional template name

**Comment by timlinux** [comment]
```
printMap(templateName=None)
printReport(templateName=None
```

Can use a default report when none is provided. Will use the current state of the canvas for report extents.

**Comment by lucernae** [comment]
List of TODO:
- [ ] The IF should be able to create Map Report and Table Report from two different function
- [ ] The dock will be able to call the IFs print function in a dialog.

**Comment by timlinux** [comment]
Can you give a status update on this @lucernae . Can you get it done for 3.5?

**Comment by timlinux** [comment]
OK moving to 3.6

**Comment by Gustry** [comment]
It could be nice to do this one @lucernae.

**Comment by lucernae** [comment]
Woops, 4.0 and we still haven't done it.
Needs to have impact_function serializable first in dock.

**Comment by timlinux** [comment]
@myarjunar can you take this over. Please add a flag to the IF to allow suppression of report generation (e.g. for use when testing).

**Comment by lucernae** [comment]
Just a note again. We need to make impact function serializable for this. That's the blocker.
The idea is, report generations now very stateless, it needs information from impact function. However at the moment we don't store impact function object in the dock, so it got lost when we run another impact function or click a different impact layer.
So, impact function object needs to be regenerated again.

**Comment by Gustry** [comment]
But we are already generating reports at the end of the IF already, so why do we need to serialize the IF ?

**Comment by lucernae** [comment]
Because if we click another impact layer, we don't have the IF object, CMIIW.
If we didn't make IF object or provenance serializable, we can only generate report after impact function run.
I think the point of this issue is to have impact function able to generate PDF whenever we want.
Also, ideally only impact report knows the location of the generated report. If we put impact_report object inside IF object, then we need IF object just to show impact table in the dock or pdfs.
Right now, we do it in hacky ways to use static naming convention for report result (so I can show it without IF object). If the name is dynamic, again we need IF object, to resolve the filename.

**Comment by timlinux** [comment]
Maybe in 4.3 we can look at this again - we should be able to retrieve the needed state from the project variables now? Or make a little helper that can deserialize an IF from the project variables?
