### ISSUE TITLE
BUG: Building Impact Function for Volcano Hazard Point

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#2677]
# Problem
Error to run building impact function for volcano hazard point

# Detail
In InaSAFE Training last week in The National Development University, Yogyakarta, I taught participant to run volcano impact function using InaSAFE. As usual, we told them that for volcano impact function they can using 2 types of vector hazard data for volcano. First one is using hazard polygon which is hazard zone volcano and the other is hazard point which is peak location of volcano.

When we run volcano using hazard polygon for buildings impact, it went well. However, when we run to see building impact using volcano hazard point, we found error in InaSAFE dock. It said there was **AttributeError**. Then, I try to using smaller area to run this impact function but the result still same as before.

# Screenshoot
![volcano_impact_building error2](https://cloud.githubusercontent.com/assets/2534179/13734421/593ba718-e9d0-11e5-8360-f3e68486dc62.PNG)

![volcano_impact_building error3](https://cloud.githubusercontent.com/assets/2534179/13736635/c68e85f2-e9e8-11e5-920c-08c9bc4f5f9b.PNG)

![volcano_impact_building error](https://cloud.githubusercontent.com/assets/2534179/13734425/6125acee-e9d0-11e5-995a-522a97096262.PNG)

# Platform
Windows 10 64 Bit
RAM 8 GB
QGIS 2.8.6 Wien (Long Term Release)
InaSAFE 3.2.6

cc : @timlinux @ismailsunni @samnawi

**Comment by samnawi** [comment]
@harrymahar I think this problem occur because of the field that decided in the keyword has a "Null" value.
I've try to change the keyword from your data, decide new field in the keyword that don't have "Null" value, and the IF is working properly.
Also when I try to use the similar data from data.inasafe.org (working properly), and then I try to change the keyword to the field that have "Null" value, apparently the IF become error.

![selection_100](https://cloud.githubusercontent.com/assets/8871958/13736825/a20ae002-e9ea-11e5-9b94-43d6fb8d0031.png)

# Proposed Solution
Make IF handle "Null" value. Maybe can automatically change to "no data", like "Null" in the number type, change to "0". So in the result will classified as " no data".

How about you @Charlotte-Morgan ?

**Comment by harrymahar** [comment]
Yeah I think solution from @samnawi is great solution for this problem because we cannot avoid this situation especially if we use OSM buildings as exposure data. In OSM data some fields including amenity will automatically "NULL" if there is no information added in it when we digitize it to OSM. 

However, HOT Indonesia at the moment working on OSM Indonesia presets that will be used in our OSM mapping activities in the future. With that presets, information about object types will be added in Building Field as well as in Amenity field. In other words, we can reduce those "NULL" information in OSM buildings.

@Charlotte-Morgan @timlinux @ismailsunni

**Comment by Gustry** [comment]
With the new value mapping when you assign your keywords, this error shouldn't appear anymore. Every buildings should go to `Other` by default.

Feel free to reopen if the problem occurs again.

**Comment by Charlotte-Morgan** [comment]
hi @harrymahar - I would strongly suggest you revisit all training materials and update key words. In future key words will automatically migrate, but if you data have older kw they may need attention to fit the new kw system.
