### ISSUE TITLE
Realtime EQ filtering on the website

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2697]
@samnawi could you please add your feedback to this ticket on filtering on the website. In particular your feedback on MMI, timeframe and number of records.

**Comment by Charlotte-Morgan** [comment]
We have received some feedback from users about the way EQ events are listed on the realtime page. The feedback related to the number of records shown etc as above.

@lucernae  - grateful if you can tweak the interface once you get the details of the feedback

**Comment by samnawi** [comment]
Hi @easmetz If we look at the earthquake realtime hazard website, I think too many information in there. So, the user will confuse to looking for the latest destructive earthquake, the latest earthquake felt, or something like that. All of them mixed in one place.
If we look at BMKG website, they just show the 60 last earthquake and 20 last earthquake felt. They separate it. 
From my perspective, the Realtime EQ website like a EQ database. User can find the shakemap data in here.
I just propose for the number of data that show at the first time, just shown maybe 20 last EQ. So, user not confuse to see the information at first sight.
I still confuse to decide a filtering about the magnitude, because if we filter just magnitude >= 5, sometime magnitude <= 5 also felt by people with high intensity if the epicenter in a land and shallow depth.

**Comment by lucernae** [comment]
Do we also want to separate the earthquake list in realtime?
What about the number of points in the map? Now it is based on the total filtered shake.
Do we want to reduce its number too?

**Comment by samnawi** [comment]
@lucernae For the number of point in the map, I think its better to show based on the filter. So the people not to difficult to find the newest event in the map.

For the future :
Could we also coloring and sizing the symbol based on the magnitude and depth / the time of an event (.... days/weeks ago)?

**Comment by samnawi** [comment]
Hi @lucernae 
:+1 for this element
![image](https://cloud.githubusercontent.com/assets/8871958/14974508/e8637e22-111f-11e6-8694-19a02e304afe.png)

As my comment on [above](https://github.com/inasafe/inasafe/issues/2697#issuecomment-200693302), could we add one filter again for felt earthquake? Because in some event, the EQ < 5 magnitude has a destructive impact.

Refers to this :
http://data.bmkg.go.id/gempadirasakan.xml
http://bmkg.go.id/BMKG_Pusat/Gempabumi_-_Tsunami/Gempabumi/Gempabumi_Dirasakan.bmkg

**Comment by Charlotte-Morgan** [comment]
please see #2696 for some comments

@ivanbusthomi

**Comment by timlinux** [comment]
How far are we with this @lucernae

**Comment by lucernae** [comment]
Felt Earthquake also added.
