### ISSUE TITLE
The realtime flood landing page list should be more informative

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2738]
### Problem

The flood landing page is not very informative in the table. @samnawi or DMI team can you provide some input on to how to make it more useful. I am thinking the following:
- [ ] Remove interval column and rather add it as text in the description. e.g. `6 hour report for April 21, 2016 at 16h00`
- [ ] We need a download button for the hazard
- [ ] Search box makes no sense - better to have support for filtering by date
- [ ] We could show as well the number of people affected and the number of RW's flooded in the table.

**Comment by samnawi** [comment]
Hi @timlinux 

> **Remove interval column and rather add it as text in the description. e.g. ``6 hour report for April 21, 2016 at 16h00``**

Did you mean this column?
![image](https://cloud.githubusercontent.com/assets/8871958/14973999/a123f164-1119-11e6-8965-ad471b90e344.png)
I agree about it, and proposed to add the new column to put the map ID
![image](https://cloud.githubusercontent.com/assets/8871958/14974067/58dffcc6-111a-11e6-9939-bc1a8ec00c9a.png)
The time and interval column, changed by the description that you mean.

I think the current information in the table little bit confusing, because there is information about time (that update every hour), but in the other column, there is information about interval (every 6 (hours....??)).

> **We need a download button for the hazard**

Yes, I agree about it. similar with the EQ realtime that provide a download button for the data.

> **Search box makes no sense - better to have support for filtering by date.
> We could show as well the number of people affected and the number of RW's flooded in the table.**

Yeah, It's better to put the filter function in there. Much less if we also put the number of people affected, and the number of RW's flooded.
I think if we show the affected number, we can also give the sort tool in that column.

Proposed from me, 
For the map, because it just for Jakarta, maybe the extent of the map just show the Jakarta.
For the information of the map, Could we show the latest information according to the information that show in Petajakarta?

Thank you.

**Comment by ivanbusthomi** [comment]
Visualizing input from mas @samnawi and @timlinux , here is what i picture :
![res](https://cloud.githubusercontent.com/assets/7351977/15203467/5420914e-182e-11e6-9ea5-4e8018f1b66a.png)

Notice that :
* The map extent is automatically at Jakarta
* Added People Affected and RW Flooded columns
* Filter function by date, and optional input threshold number of people affected and/or RW flooded
* icon for pdf report/map is the same as in earthquake real time map (I propose this to avoid confusing user, because both button in earthquake and flood basically does the some function, right? )
![icon](https://cloud.githubusercontent.com/assets/7351977/15203559/311c7c3e-182f-11e6-80d5-63547a916f48.PNG) :point_left: this one is in the earthquake, and this one :point_right:  ![icon flood](https://cloud.githubusercontent.com/assets/7351977/15203647/eab99910-182f-11e6-94e6-6bef40e175a3.PNG) is in the flood
* Just like the first column, the second and third column must be able to be sorted.

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
