### ISSUE TITLE
Using IF metadata to store the styles

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2765]
### Problem

Currently, the style for each IF is stored in the impact layer (SafeLayer).
The code is written in the main function of the IF.
Some IF don't use the colour code.
### Proposed Solution

I would like to set the style in the IF metadata because I think that the style is not very appropriate in the `run` method of the IF. I would like to move it in the metadata section. It will allow us to return a QgsMapLayer instead of a SafeLayer from the IF.
The style will be a property in the IF and the dock will be able to read the style.

Moreover, we can create a list of colours. For now, every IF defines their owns colours (affected, not affected, dry, wet ...) We can make them more uniform across IF.

CC : @timlinux @ismailsunni

**Comment by timlinux** [comment]
Yeah I really like this idea. Maybe it is also good to transfer these values to the impact layer xml metadata or to the impact_data so that if the data is provided without a style file we can actually generate the QGIS style again. I can see use cases where for example we want to generate a table with histograms as per Martin's proof of concept and we want the bars to match the colours assigned to the style of the layer classes.

**Comment by Gustry** [comment]
We can now close this ticket with inasafe v4.
