### ISSUE TITLE
[BUG] For the flood scenario with land cover, function in the 'might' column did not appear

### ISSUE THREAD

**Issue by raniedwianugrah** [inasafe/inasafe#2809]
### Problem

A function in the 'might' column did not appear when I processed the land cover vector, flood vector and Jakarta boundary data in InaSAFE Dock. The land cover keywords are defined. 

![bug_flood_landcover_vector](https://cloud.githubusercontent.com/assets/2528195/15420006/3c37fae2-1e94-11e6-86df-e1ac691dd1b4.PNG)
### Environment

InaSAFE 3.4.0 dev-master
QGIS 2.8.9
Windows 7 32 bit/64 bit
Windows 10 64 bit 
### Data Used
1. Jakarta_Flood_18113_WGS84.shp
2. Jakarta_landuse_WGS84.shp
3. Jakarta_District_Boundary_WGS84.shp

CC: @timlinux @ismailsunni @samnawi

**Comment by Gustry** [comment]
There is no impact function Flood on Landcover that's why the dropdown menu is empty and why the `run` button is disabled.
The only way to use landcover for now it's to use the generic IF. For that, you need generic keywords on your flood layer (in the keyword wizard, you should set your layer as generic, not as a flood layer).

But I agree there is a kind of bug, as InaSAFE should warn you `No IF available`.

**Comment by raniedwianugrah** [comment]
Oops sorry, we think the function is available in flood scenario.

**Comment by ismailsunni** [comment]
@gustry do you think set the value of the IF combo box to `No IF available` will solve the bug?

**Comment by timlinux** [comment]
To be more precise - we don't have flood specific IFfor landcover - you should be able to do it with the generic polygon on IF landcover analysis. In the future #2987 will address this.

@ismailsunni reckons if the vector classification is set to flood rather than generic, then no IF will show.

**Comment by timlinux** [comment]
We should be able to close this when #2987 gets implemented.

**Comment by Gustry** [comment]
We don't have this combobox anymore in InaSAFE V4. I'm closing this ticket.
