### ISSUE TITLE
Color Ramp For Symbology

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2828]
### Problem

We found the inconsistency color ramp for the impact symbology.
**Flood VS Polygon**
![image](https://cloud.githubusercontent.com/assets/8871958/15497923/425c0e78-21c7-11e6-8aba-56aba7d98fa7.png)

**EQ Raster VS Building**
![image](https://cloud.githubusercontent.com/assets/8871958/15497956/670a3fa6-21c7-11e6-8622-a7049e7b66d0.png)

**Classified Volcanic Raster Hazard on Buildings**
![image](https://cloud.githubusercontent.com/assets/8871958/15498073/12604616-21c8-11e6-84d3-5cdfd448ce11.png)

**Classified Polygon EQ Hazard on Polygon People**
![image](https://cloud.githubusercontent.com/assets/8871958/15498121/5adbd57c-21c8-11e6-80e6-35a8758d2792.png)

@felix-yew and @ivanbusthomi Would you like to add the table that related to this issue from systematic testing?
### Expected Behaviour

Could we use the same color ramp to presenting the classification in the symbology?
### Environment
- InaSAFE : 3.4
- QGIS :  2.8.8 / 2.14.1
- OS :  Win 7 64 Bit
### Proposed Solution

Make it Happy

CC : @timlinux @Charlotte-Morgan @ismailsunni

**Comment by ismailsunni** [comment]
hi @samnawi, do you have preference for the color ramp? Which one that we can pick as the universal color ramp? Does it happen only on 4 IF above? Or should we make it general?
I think we need at least 4 color:
1. Not affected (green ?)
2. Low (yellow ?)
3. Medium (orange ?)
4. High (red ?)

It can be more specific to RGB value, since my green is not always the other green.

@Gustry and I had discussion about this. We want to put it in IF metadata. By that way, we can share the color ramp across the IFs, and have the same color ramp.

**Comment by Gustry** [comment]
@samnawi It's on my todo list for InaSAFE 3.5 https://github.com/inasafe/inasafe/issues/2765
For now, each IF creates their own color. I would like to refactoring the styles.

**Comment by Charlotte-Morgan** [comment]
hi @easmetz - you might be interested in this for the RFC on standards #2920

**Comment by Gustry** [comment]
In V4, we are now using 8 colors defined here : 
https://github.com/inasafe/inasafe/blob/develop/safe/definitions/styles.py#L11
