### ISSUE TITLE
Different of value in each hazard zone in population analysis

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#2856]
### Problem

In some hazard, there are some problem after analysis and print the table.

**1. Earthquake (vector) and Population (vector)**
![image](https://cloud.githubusercontent.com/assets/13621886/15569775/e01ff908-235c-11e6-990f-9098a9a17019.png)
In this case, **total affected people in aggregation result is not correct**. Related to the value of each hazard zone is much different. There is a inconcistency using moderate hazard zone, generally use medium.

**2. Earthquake (vector) and Population (raster)**
![image](https://cloud.githubusercontent.com/assets/13621886/15569932/b930fc1a-235d-11e6-97a4-ed77414ba5ba.png)
In this case, in medium hazard from in aggregation is very different with no aggregation result. The different value was similar case with unaffected population.

**3. Tsunami (vector) and Population (raster)**
![image](https://cloud.githubusercontent.com/assets/13621886/15570176/f28bf6a8-235e-11e6-822f-3573191f8af5.png)
In this case, same as point 2.

**4. Volcanic polygon (vector) and Population (vector)**
![image](https://cloud.githubusercontent.com/assets/13621886/15570260/5434b516-235f-11e6-8169-025b7a5a19d0.png)
In this case, same as point 1. The different result analysis is in the "Volcanic Hazard Zone I" and total affected people is more than 9.200 in aggregation result.

**5. Flood generic class (vector) and Population (vector)**
![image](https://cloud.githubusercontent.com/assets/13621886/15570318/b7631b82-235f-11e6-8cef-0cf207bc6bab.png)
In this case, in each hazard zone have the different value, even in the no aggregation result has not correct calculated.

I have summarize the problem in to the table.
![image](https://cloud.githubusercontent.com/assets/13621886/15570533/b5036260-2360-11e6-9718-e781655148da.png)
### Expected Behaviour
- Fix the value of result analysis in each hazard zone.
- Fix the calculated of affected population.
### Environment
- InaSAFE : 3.4.0
- QGIS : 2.8.8 and 2.14.1
- OS : Win 7 64-bit
- Data used :
  - Earthquake : https://www.dropbox.com/sh/ctu8ij5a6e7xcw2/AABHViyG0J1m6xe-tEypSCMsa?dl=0
  - Tsunami : https://www.dropbox.com/sh/pk1mm5kwobonkat/AAAHEAfXAlQkFbQv1ar6DFT0a?dl=0
  - Volcanic : https://www.dropbox.com/sh/5q05fy45ai53n4a/AADBaqNKIp-Sky-OnDb-6V81a?dl=0
  - Flood : https://www.dropbox.com/sh/pk1mm5kwobonkat/AAAHEAfXAlQkFbQv1ar6DFT0a?dl=0
### Proposed Solution

Make it happy :smile: 

**Cc:** @Charlotte-Morgan @timlinux @ismailsunni @samnawi @ivanbusthomi

**Comment by samnawi** [comment]
After we doing the InaSAFE analysis to develop the Tsunami & EQ contingency plan in Ambon last week, I also found this problem in Tsunami Classified Polygon Hazard on Polygon People.

This is the result
![image](https://cloud.githubusercontent.com/assets/8871958/15845681/8316ad00-2c9f-11e6-96b8-2bbf8c68a0e2.png)

Thank you.

**Comment by ismailsunni** [comment]
Hi @felix-yew 
It seems your link doesn't contains the data (shp, tif, etc). It only has xml, qml, qpj, lic, prj, and keywords. Can you update it?

**Comment by ismailsunni** [comment]
I can replicate the issue by using the standards test data in InaSAFE. My finding only has small different number, but perhaps it because the data set is small. If we use bigger data set, the number will be much bigger. I also found there is perhaps something wrong with the aggregation. See my result below using Population, Volcano KRB, Grid, and District of Jakarta layer :

1. Aggregation on District of Jakarta
<img width="1393" alt="screen shot 2016-07-12 at 13 44 47" src="https://cloud.githubusercontent.com/assets/1421861/16757760/331b9d24-4838-11e6-9718-772c6a10623b.png">

2. Aggregation on Grid
<img width="1400" alt="screen shot 2016-07-12 at 13 44 18" src="https://cloud.githubusercontent.com/assets/1421861/16757756/2c191326-4838-11e6-8cf8-4a47eb45ea29.png">

3. Entire area
<img width="1396" alt="screen shot 2016-07-12 at 13 45 04" src="https://cloud.githubusercontent.com/assets/1421861/16757880/ba559254-4838-11e6-8c65-e8e375cdae45.png">

See the yellow arrow and the blue box. The first one (by district) is missing the blue box part. The second one (by grid) is missing the yellow arrow one.

**Comment by felix-yew** [comment]
Hi mas @ismailsunni 

So, the problem is in the area of interest, if we want to use the big area analysis the number result will be affected, too? If the range number is not huge, I think is okay, it causes by the rounding system. But, **if the range number of affected is huge, i.e. more than 1.000 people, maybe we have to fix it**. Because the number of affected in each hazard zone is very **important to the users, especially the decision maker**, to make a scenario and influence the risk assessment in the real event.

Make it happy.

**Comment by Gustry** [comment]
We made a big refactoring in version 4.0. I think we can close this ticket.

**Comment by ismailsunni** [comment]
Yes, we can close this ticket. We don't use aggregate anymore which cause the problem. IIRC.
