### ISSUE TITLE
Failure to select impact layer when using impact layer merger

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2909]
### Problem
Using the Run Basic inasafe I am unable to merge two impact layer after successfully running `Run InaSAFE Analysis for Building` and `Run InaSAFE for population`. The two analysis generate correct result but when I launch the impact layer merger the drop down for selecting which impact layer I should choose is greyed out.

![result_image](https://cloud.githubusercontent.com/assets/2510900/15824548/fc896808-2bff-11e6-8c8d-b188386b6ac9.png)

After generating results I get.
![merge_1](https://cloud.githubusercontent.com/assets/2510900/15824586/285b6ada-2c00-11e6-86ec-c58129ea0994.png)

### Expected Behaviour
Allow drop down to be populated by impact layers.

### Environment
* InaSAFE : 3.14
* QGIS : 2.14.1
* OS : Ubuntu 16.04
* Data used :
  * Exposure :  ` Run Basic InaSAFE/DKI Jakarta/02 Exposure Data/Jakarta_Population_WGS84.tif ` and `Run Basic InaSAFE/DKI Jakarta/02 Exposure Data/Jakarta_buildings_WGS84.shp `
  * Hazard : `Run Basic InaSAFE/DKI Jakarta/01 Hazard Data/Jakarta_Flood_HKV_WGS84.tif `
  * Aggregation : Entire Area

### Proposed Solution
Ensure the drop down is prepopulated correctly.

**Comment by ismailsunni** [comment]
I can fix the impact layer population problem (see https://github.com/ismailsunni/inasafe/tree/fix_2909_impact_layer_merger)

But, we have another problem. It seems the impact merge tool parsing the postprocessing_report html. It's very fragile and we are our way to make a standard impact report. Also, we have remove the postprocessing_report from the layer's keywords. So, we need to get the data from the json.

Any comment @timlinux ?

**Comment by timlinux** [comment]
Ok this one is going to be a bit painful to fix. @Charlotte-Morgan I am going to rope you into the conversation here because I want to suggest that we:

* remove the impact merge tool for 3.5
* do some thinking about our architecture for post 4.0 to support running multiple impact functions (same hazard multiple exposure) in one go.

Any other approach is going to be inherently fragile. The current implementation uses parsed html from the report to construct the report. We could do a halfway house improvement of using @ismailsunni's nice new metadata stuff but we still have stope for fragility - the user needs to do a very precise set of actions in order to be able to merge impacts, hence my proposal that we rather do all the analysis variations at once so that we can completely control the environment and ensure the results are consistent.

**Comment by timlinux** [comment]
As a one liner, my short term proposal for 3.5 is that we remove this tool

**Comment by timlinux** [comment]
@Charlotte-Morgan What do you think of my suggestion?

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - I personally have no problem with removing the tool. I have never used it and am not sure its even covered in our training. I expect there may be people who use it and if they pop up we can deal with issues then. I think that with new reporting, we may have cleaner ways to combine analysis results in the future.

+1 to remove in 3.5

**Comment by timlinux** [comment]
@Charlotte-Morgan Great - I will remove it... 

@adissadis please note the above discussion as it will impact your documentation work too I think....
