### ISSUE TITLE
The impact summary is different between road and building IF

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2951]
### Problem
It seems that reports haven't the same layout.
For instance with a building layer : 
![if-summary-1](https://cloud.githubusercontent.com/assets/1609292/16579804/bd962b6e-42a1-11e6-957b-ce21554f15ec.png)

And with a roads layer : 
![if-summary-2](https://cloud.githubusercontent.com/assets/1609292/16579807/c2bbc4be-42a1-11e6-9eac-a07ced00683e.png)

* The question is missing.
* Unaffected vs not affected
* But the main difference is that the impact summary is using rows for buildings (without headings), however the impact summary is using columns for roads.

### Expected Behaviour

Reports should have globally the same layout.

### Proposed solution
Something to add to the coding standarts @Charlotte-Morgan and @easmetz ?

See also : 
* https://github.com/inasafe/inasafe/issues/2920
* https://github.com/inasafe/inasafe/issues/2746
* https://github.com/inasafe/inasafe/issues/2902

**Comment by Charlotte-Morgan** [comment]
yes - this should be covered by #2920

**Comment by timlinux** [comment]
I want to propose that we standardise the layout so that the second example would rather have the labels down the left (and add a note in #2920 that impact summary labels should always be down the left). So we would have rather:

Name | Length (m)
-------- | ---------------
Road type | 12321
Flooding in threshold of 1m | 122
Unaffected | 12222
Total | 4345643

**Comment by timlinux** [comment]
So what we propose is to have the vertical layout as per the first screenshot above for the impact summary table, and then the layout (breakdown by road type / building type) as per the second screenshot above.

**Comment by Gustry** [comment]
I just updated screenshots to show only the impact summary.

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry -  agree there is a problem.

For the impact summary - this is a general report and only needs to include affected, not affected. These should be row headings.

However, the impact table is a more detailed report by type eg road or building type. Since the road or building type could be many categories, these become the row headings and the affected is now split into multiple columns according to thresholds or hazard zones.

If we refer to the examples you include in #2920; then the buildings example is my preference for how to do things.  The impact summary for roads needs to be turned around as per my example for tsunami on roads in #2920.

![image](https://cloud.githubusercontent.com/assets/5743135/16682948/5bcacf6a-4527-11e6-9341-3912856109ed.png)

**Comment by timlinux** [comment]
@Charlotte-Morgan good I think we are all on the same page here. So for now we will pivot the road summary table and remove the exposure category rows....@gustry hopefully then we can use a single function for the IF summary table and get rid of some duplication....

**Comment by Gustry** [comment]
This is the new impact summary for roads : 
<img width="413" alt="screen shot 2016-07-12 at 2 15 34 pm" src="https://cloud.githubusercontent.com/assets/1609292/16758335/2b03c258-483b-11e6-9a9e-37e5b358b184.png">

I'm going to close this one and we can come back on the headings on the other ticket #2902

**Comment by timlinux** [comment]
That looks good thanks @Gustry
