### ISSUE TITLE
IFCW report wizard should be exapandable

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2975]
### Problem

After running impact analysis the reports that is generated on IFCW cannot be visualized on single page to maximize the screen resolution of a user before deciding on printing. 

![selection_008](https://cloud.githubusercontent.com/assets/2510900/16257912/8bb9c790-385b-11e6-8eee-44a11119e61a.png)
### Expected Behaviour

Make the wizard expandable.
### Environment
- InaSAFE :  3.5
- QGIS :  2.14.3
- OS :  Ubuntu 16.04
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

Make the wizard expandable.

**Comment by borysiasty** [comment]
Please note I spent days, trying to control the MessageViewer's size, e.g. by setting its maximumHeight dynamically (depending on the window size), without any success. If we don't restrict the maximum height of the whole tab widget, all steps will be taller than the wizard window (involving a vertical scroll bar, what looks really bad :) )

Additional investigations are needed to finally find a way to only put the MessageViewer to a scroll area, instead of the whole tab widget...

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry and @timlinux 
I think i'm spotting the same issue and would like to see more of the wizard especially as all the user help is hidden at the bottom of the scrolling.

Expanded wizard window still uses limited real estate
![image](https://user-images.githubusercontent.com/5743135/29104511-6c498514-7d09-11e7-89c3-47dba0434a5a.png)
But all the user help is down the bottom 
![image](https://user-images.githubusercontent.com/5743135/29104530-86c3d8d6-7d09-11e7-822b-4bf31c5b20a7.png)

maybe the alternative is to use the space below for the help text (not that wizards need help)

**Comment by Gustry** [comment]
See #4411 and PR #4465

**Comment by ismailsunni** [comment]
Fixed in #4465
