### ISSUE TITLE
Wrong building classification in ClassifiedRasterHazardBuildingFunction

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2990]
### Problem
While running ClassifiedRasterHazardBuildingFunction with a Ash hazard on buildings, the result shows a `Not affected` building in the center of the ash cloud (high hazard zone)

![3859](https://cloud.githubusercontent.com/assets/1609292/16406001/d7011ac8-3d0b-11e6-8735-c2da39d955b4.png)

### Expected Behaviour
Classify the building in the high hazard zone.

### Environment
* InaSAFE : Develop
* QGIS : 2.14.3
* OS : 14.04
* IF : ClassifiedRasterHazardBuildingFunction
* Data used : https://github.com/inasafe/inasafe/files/330234/2969.zip
  * Exposure : Buildings
  * Hazard : Ash

**Comment by Gustry** [comment]
After investigation, it seems a duplicate of #2969

**Comment by Gustry** [comment]
I can still replicate the issue after the fix #2999 from @ismailsunni 
My keywords are up to date and I'm using develop.

Since #2999, the IF is using strings to build the legend. But the attribute table is not fully translated so it's broken if we are using not using QGIS in English. I made a PR #3015 

Tickets which are related to the same IF : 
* #2969 Minus number in the Not Affected Result
* #2985 Impact results layer not visible after running volcanic_ashonstructure
* #2858 Symbology problem in Classified Volcanic Ash Raster on Vector exposure

**Comment by ismailsunni** [comment]
I tried to investigate it, I found I did some silly mistake. If you checked the keywords in the hazard layer in that link for the data, you will find :
<img width="1112" alt="screen shot 2016-08-05 at 10 30 52" src="https://cloud.githubusercontent.com/assets/1421861/17425483/fca4403e-5af7-11e6-8f56-0adf22bd0c9c.png">
So, some values are not mapped yet. And it will considered as not affected. Thus, we got this result:
<img width="520" alt="screen shot 2016-08-05 at 10 31 07" src="https://cloud.githubusercontent.com/assets/1421861/17425489/0e4c606e-5af8-11e6-92b9-774ffcf7cf13.png">
The green in the middle one should be affected, since it's in the red zone. But, the value is not mapped for that red zone, that's why it got classified as not affected, and become green.

If we update the keyword to the proper one like this:
<img width="1099" alt="screen shot 2016-08-05 at 10 31 55" src="https://cloud.githubusercontent.com/assets/1421861/17425509/3c93aa2c-5af8-11e6-9c13-d2333a4cebc4.png">
You will get the result that looks much better:
<img width="548" alt="screen shot 2016-08-05 at 10 31 40" src="https://cloud.githubusercontent.com/assets/1421861/17425512/48efbdc4-5af8-11e6-83fe-ede304093761.png">

So, I am sure, this is not a  bug or regression, but a feature (which become a bug because I did the silly mistake, didn't map all values).
