### ISSUE TITLE
We need raster flood on population polygons

### ISSUE THREAD

**Issue by marawiti** [inasafe/inasafe#2992]
### Problem

inasafe cant use flood raster hazard and population polygon exposure to estimate % of population at risk
### Expected Behaviour

unkown
### Environment
- InaSAFE : 
- recommended Data
  - Exposure :  population polygon
  - Hazard :  flood raster
### Proposed Solution

create a module with ability to aggregate the above data, since raster format is appropriate to present flood hazard while population exposure is effeciency presented by polygon

**Comment by timlinux** [comment]
@marawiti thank you for your issue report. Could you help us by explaining exactly what steps you followed and sharing the datasets you used? We do actually have support for polygon flood on population areas, so as a temporary work around you could manually convert your raster flood data to polygon vectors by:

* classifying the flood dataset so that cells now represent flood class (e.g. low, medium, high flood depth)
* polygonising the resulting classified raster
* using the new polygon layer for your classified flood data, you could assess the potential impact of this dataset on your population data

In the future we would like to streamline the process (see #2987) but for the short term I suggest to try the manual approach described above. Feel free to follow up here if you need help to do that.

**Comment by timlinux** [comment]
I renamed the title of this issue to make the request clearer...

**Comment by marawiti** [comment]
tanks timlinux, i am a using inasafe version 3.4.2.. what is the current version?

**Comment by marawiti** [comment]
i need to use it so that i can contribute more

**Comment by Gustry** [comment]
Yes, no problem, 3.4.2 is the latest version.

**Comment by Gustry** [comment]
This is done in version 4.0. I'm closing this ticket.

**Comment by marawiti** [comment]
Tanks so much
