### ISSUE TITLE
set analysis area accumulates

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#3018]
### Problem
If you click 'set analysis area' more than once, additional analysis areas render on top of existing ones
### Expected Behaviour
Clicking 'set analysis area' should remove the previous one and replace it with a new one.  
### Environment
* InaSAFE : 3.4.2
* QGIS : 2.14.3
* OS : Ubuntu
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

**Comment by timlinux** [comment]
This duplicates https://github.com/inasafe/inasafe/issues/1746

The problem is we can't reliably duplicate it to fix it. I did some testing against current develop and it is still not doing this for me. Please reopen if you can provide concrete steps to replicate.

![qgis](https://cloud.githubusercontent.com/assets/178003/17018470/19032980-4f62-11e6-901d-65df175c5aa9.gif)
