### ISSUE TITLE
We need to make map titles consistent

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3083]
### Problem

Titles vary from map to map. We need consistency across maps.

### Proposed Solution

Make all report titles consistent with the new standards found in https://github.com/inasafe/inasafe/blob/develop/docs/reporting-standards.md

### cc
@Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux - this PR does not quite fix all the map titles. I have reopened the ticket.

# Problem
all map titles have changed but are not quite right

Map titles for raster hazard data seem to be fine.
Map titles for vector hazard data seem to be treated as generic data.

In the standard, the generic option refers to when the hazard keyword is generic, not when the IF is generic.

The result is in some cases a regression. Eg for an earthquake hazard map in Nagekeo, the map title used to say "Buildings affected by each hazard zone"
it now says "Buildings affected"
we would like it to say "Buildings affected by earthquake hazard"


# Proposed action
please review and fix or hold for 3.5.1

**Comment by timlinux** [comment]
Hi @Charlotte-Morgan 

> In the standard, the generic option refers to when the hazard keyword is generic, not when the IF is generic.

Oh ok understood, will fix.

**Comment by timlinux** [comment]
Hi @Charlotte-Morgan 

Ok I have implemented the fix for InaSAFE 3.5 (see PR at #3146)

Here is an example with generic IF and vector hazard + exposure (taken from your lovely training projects):

![screen shot 2016-08-11 at 3 32 26 pm](https://cloud.githubusercontent.com/assets/178003/17590631/bcef875e-5fda-11e6-869d-162d9e347251.png)

Just two things to note: 

1) In the standards doc it refers to buildings as exposure type. Long ago there was a debate about this and it was decided to use the term 'Structures' rather than 'Buildings'  because the exposure layer could also include other types of things like power substations, city infrastructure etc. I don't mind changing it back to buildings as it probably does cover the more general use case. So either we should change the definitions to Buildings, or the standards doc to Structures.
2)I'm not sure if I mentioned in my original patch, I have changed the generated layer name for the impact layer to use the same text as the map_title. It seems more logical to me and the previous implementation was a hodgepodge of different naming styles - everything is consistent now. If you prefer another system, we can document it in the standards doc and I will implement it.
