### ISSUE TITLE
BUG: version 3 key words did not automatically update in v3.5

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3150]
# problem

Volcanic ash data with 3.3 key words did not update to v 3.5 when loaded.
# proposed solution

Make it happy :)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
It seems I was wrong in gitter channel. The version is kept as it is. It will only updated when you assign the keyword via keyword wizard.

I think this is more logical since we don't want to change anything without user knows what happened.

If the old keyword is not supported by the current InaSAFE's version, we just tell the user that the keyword needs to be updated.
Since InaSAFE version 3.5 supports 3.4 and 3.3, we don't need to change anything in the keyword. 

Let me know your preference behaviour...

cc @timlinux @felix-yew @ivanbusthomi @lucernae

**Comment by Gustry** [comment]
I'm closing this ticket as version 4 is going to be released.
