### ISSUE TITLE
Realtime Flood - not working

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3229]
# problem

there are many floods occuring in Jakarta. Flood hazard data appear on PetaJakarta but we have not had any reports in InaSAFE Realtime Flood since the end of August.
# proposed solution

make it happy as fast as possible please

see also #3176
# cc

@samnawi

**Comment by lucernae** [comment]
@Charlotte-Morgan Realtime flood worker somehow stopped working since 22nd September. So, we lost our flood record since that day. It also turns out that the same worker that supposed to send emails to me when the other is down is the one who is down, so I didn't get any notifications.

I revived the worker as of now. I also checked again in September we don't have any petajakarta data that contains flood (no report generated) until 22nd September. From 22nd we were disconnected from petajakarta.

**Comment by timlinux** [comment]
@lucernae Any idea why there were the floods between end of August and 22 September went to? See screen below:

![screen shot 2016-09-26 at 11 52 53 pm](https://cloud.githubusercontent.com/assets/178003/18853264/7dddc63c-8444-11e6-90ab-5bd7e19ba39c.png)

**Comment by lucernae** [comment]
Fixed this by separating the celery worker queue.
As for @timlinux 's question. If there were no flood, it will not be saved to InaSAFE django.
But for the case 22nd September we were disconnected for several hours.
