### ISSUE TITLE
GeoNode can not upload part of file raster format

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3304]
### Problem

When I try to upload a raster file in [http://geonode.inasafe.org/](url) not all of the raster files can be uploaded properly. See the image below :
![unsupported type_upload raster](https://cloud.githubusercontent.com/assets/13621886/19337415/2e44bb3c-913f-11e6-9d25-24fafc5a424d.jpg)

When I continue to upload files and/or I delete the unsupported file, but can not work properly. Error like image below :
![unsupported type_upload raster_object](https://cloud.githubusercontent.com/assets/13621886/19337852/ee330680-9142-11e6-9a67-ab0e8b5641be.jpg)
### Expected Behaviour

The raster files package can upload properly and support the analysis.
### Environment

GeoNode

Hazard raster : [Ambon_Banda_Tsunami_FD_30m_WGS84.zip](https://github.com/inasafe/inasafe/files/526381/Ambon_Banda_Tsunami_FD_30m_WGS84.zip)
### Proposed Solution

Make it happy :smile:

**Comment by Charlotte-Morgan** [comment]
Hey Felix

This is a huge file.
Maybe the prototype geonode is not able to work with such big datasets?

On 13 Oct 2016, at 2:52 PM, felix-yanuar-ew <notifications@github.com<mailto:notifications@github.com>> wrote:

Problem

When I try to upload a raster file in http://geonode.inasafe.org/<url> not all of the raster files can be uploaded properly. See the image below :
[unsupported type_upload raster]<https://cloud.githubusercontent.com/assets/13621886/19337415/2e44bb3c-913f-11e6-9d25-24fafc5a424d.jpg>

When I continue to upload files and/or I delete the unsupported file, but can not work properly. Error like image below :
[unsupported type_upload raster_object]<https://cloud.githubusercontent.com/assets/13621886/19337852/ee330680-9142-11e6-9a67-ab0e8b5641be.jpg>

Expected Behaviour

The raster files package can upload properly and support the analysis.

Environment

GeoNode

Hazard raster : Ambon_Banda_Tsunami_FD_30m_WGS84.zip<https://github.com/inasafe/inasafe/files/526381/Ambon_Banda_Tsunami_FD_30m_WGS84.zip>

Proposed Solution

Make it happy ?

Cc : @Charlotte-Morgan<https://github.com/Charlotte-Morgan> @timlinux<https://github.com/timlinux> @samnawi<https://github.com/samnawi> @ismailsunni<https://github.com/ismailsunni>

-

**Comment by ismailsunni** [comment]
Thanks @Charlotte-Morgan for pointing that out. 
I download it, and it was only 1.1 MB, but when I extracted it, it becomes 320MB.

Perhaps try to upload smaller size like @Charlotte-Morgan mentioned.

**Comment by felix-yew** [comment]
Thank you @Charlotte-Morgan and mas @ismailsunni, while the GeoNode is prototype but how much limitation that can be uploaded? Then we can try to test and run the GeoSAFE, too.

**Comment by gubuntu** [comment]
@felix-yew please try again on the new system. And if the problem is that the file is too big, try the back-end cli upload. Then close if fixed.

**Comment by felix-yew** [comment]
Hi @gubuntu - Sorry for the late response. I have tried to upload the data again which previously had trouble uploading. I still failed to upload it.
![image](https://user-images.githubusercontent.com/13621886/35671418-f45fdb30-076d-11e8-8843-1ea96a3f53d9.png)
The data that I upload is raster population, NT_Population_WGS84.tif, the size of file around 180 Mb.
Do you know where I can see the tutorial on how to upload the big data layer with the back-end cli?

**Comment by gubuntu** [comment]
@NyakudyaA can you assist Felix?

**Comment by NyakudyaA** [comment]
@gubuntu  Risky is going to setup btsync on the server and the data will be synced there so that it can be ingested using management commands.

**Comment by felix-yew** [comment]
Hi @gubuntu and @NyakudyaA - mas @lucernae and mas @ismailsunni have helped me to manage how to sync the data and start uploading layer if it made it into the rancher, by read the wiki of geonode. But, unfortunately I am still can not login into the rancher.

**Comment by felix-yew** [comment]
Thank you mas @lucernae @NyakudyaA @ismailsunni @gubuntu for helping me to upload big layers. I think we can close this. And maybe we can open it if we find the same problem in the future.
