### ISSUE TITLE
Is it possible to develop a multi-hazard risk assessment?

### ISSUE THREAD

**Issue by feyeandal** [inasafe/inasafe#3370]
### Problem

Since InaSAFE runs only one hazard per assessment, can we develop a multihazard risk assessment wherein we can combine two or more impact results (derived from different hazards like flood, landslides, and storm surges)?

**Comment by timlinux** [comment]
Hi @feyeandal My apologies that we missed this ticket until now. We did have a tool 'impact merge tool' that allowed you to run two analyses independently and then merge the results into a single report. In the version 4.0 code that comes out soon (and the later 3.x releases) we removed that tool because it was buggy and hard to use.

I think that multihazard is something we could do in the future but it is not on our immediate roadmap. We would need to do it by providing a modified version of hte question that lets you select more than one hazard layer and then runs the two analyses and uses both of their outputs for the combined report.

One thing we have done in the upcoming v4.0 code is to make it much easier to get raw data (tables, geometries) for the analysis results, so if you have some basic GIS skills it should be quite easy to run the two analyses manually and then produce a combined report using built in functionality in QGIS.

I'm going to close out this ticket for now - if you have some more concrete plans to get support multi-hazard assessments in InaSAFE (e/g/ by doing some local development work at NOAH) lets chat about it on the mailing list or in our Gitter chat - we would be happy to support your work from our side.
