### ISSUE TITLE
KW dialogs layout does not resize properly

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#3533]
### Problem
KW dialogs layout does not resize properly and does not take up all available space. seems like the QDialog was not given a base layout
![screenshot from 2017-01-04 20-20-35](https://cloud.githubusercontent.com/assets/233663/21655813/d35335be-d2bb-11e6-9a2b-d6cbd95ea6cf.png)

### Expected Behaviour
the content should resize nicely

### Environment
* InaSAFE : ee117250efb8aba012fb4c7b2b60146a58585f91
* QGIS :  2.18
* OS : Ubuntu
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
add base layout to KW dialogs

**Comment by timlinux** [comment]
I'm on ee117250e too and don't have the problem. In the past we had a lot of issues trying to manage the size of the wizard on small displays - the content that gets placed in the dialog is extremely variable. Our main fix is to use a scrollbox underneath the top level layout (which we do have as you can see in this image). 

![qgis](https://cloud.githubusercontent.com/assets/178003/21660026/428e05f2-d2d6-11e6-8a9e-463fedec74eb.gif)

Looking more closely at your image, it looks more like a HiDPI issue rather than an issue with top level layouts.

**Comment by ismailsunni** [comment]
Fix in #4465
