### ISSUE TITLE
Some of the Input For IFCW 4.0

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#3600]
### Problem

![image](https://cloud.githubusercontent.com/assets/8871958/21975039/f56bd7c4-dbfc-11e6-86c9-7084c4e2c2a5.png)

Today, I and @felix-yew  doing a quick view of the IFCW to be ready to release in the beta 2 version.
After we discuss with @Charlotte-Morgan we have some proposed to do soon, and to do later.

**Soon**
1. Disable Place for all hazard
2. Disable Road for cyclone
3. Disable landcover raster
4. Disable volcano raster
5. Add generic hazard (with generic class (H/M/L and for raster and vector)
6. Should show analysis extent in IFCW
7. Some of the IFCW button is not working (Generate PDF and Open in Composer)

**Later**
1. Since Place exposure is disabled (soon) :
            a. Add the population point to the population exposure
            b. For the other place (airport) --> already accomodated by structure point

Feel free to give some comment.

cc : @timlinux @ismailsunni @Charlotte-Morgan @ivanbusthomi

**Comment by Charlotte-Morgan** [comment]
Thanks @felix-yew and @samnawi - this is a good summary.
The reason we ask for some things to be disabled is because we do not have that data type - eg volcano raster  and landcover raster; or we have no intention to generate notes and action lists such as for place.
With cyclone hazard , the advice is that it is expected to run on buildings, population and landcover.

**Comment by ismailsunni** [comment]
@samnawi 
I have addressed  1, 3, 4, 5 on #3601. Can you check?

**Comment by Gustry** [comment]
@ismailsunni Do you still to work on this one ?

**Comment by ismailsunni** [comment]
Ah yes, I have done all of them.
