### ISSUE TITLE
Problem in KW wizard for flood hazard definitions:  Missing constant

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3619]
### Problem

I get this when defining the keywords for a flood layer in my postgres database:

![screen shot 2017-01-17 at 3 27 37 pm](https://cloud.githubusercontent.com/assets/178003/22013068/bb8ff580-dcc9-11e6-89f1-72176cf4face.png)

I don't think the issue is specific to the fact that the layer is in postgres.

### Expected Behaviour

A more sensible message should be shown to the user in the wizard step description

### Environment
* InaSAFE : 4.beta
* QGIS : 2.14.10
* OS : MacOS
* Data used : 
  * Exposure : n/a
  * Hazard : sri lanka flood data
  * Aggregation : n/a

### Proposed Solution

Please check where this message is going wrong and fix

**Comment by ismailsunni** [comment]
We don't have robust system to generate the step description. It happened because we change `metres_depth` to `metres` in units.py key.
In the `wizard_strings.py`, I only got `flood_metres_depth_question`, which won't be discovered since we try to find `flood_metres_question` now, like in your example.

I don't know a better way to fix it, beside renaming the variable.

But, this is not good, when we add more hazard or unit, it will give MISSING CONSTANT again.

Any suggestion @timlinux ?

I check the strings, I don't think they have common pattern.

**Comment by timlinux** [comment]
Can you point to the logic of how it is currently generated?

**Comment by ismailsunni** [comment]
@timlinux  https://github.com/inasafe/inasafe/blob/develop/safe/gui/tools/wizard/wizard_utils.py#L39
