### ISSUE TITLE
Update Landcover Classification and Fields

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3626]
### Problem
Currently, we use a very basic classifications for land cover classes. We should have a better classification and reference.
<img width="1097" alt="screen shot 2017-01-18 at 09 21 58" src="https://cloud.githubusercontent.com/assets/1421861/22048449/aea634f6-dd5f-11e6-9e58-66190024b982.png">

We also needs more field to the land cover exposure:
- [ ] Productivity Kwt/HA
- [ ] Productivity cost Million IDR/HA
- [ ] Productivity value Million IDR/HA
- [ ] Remove the feature rate

cc @fredychandra @timlinux @Charlotte-Morgan @inasafe/issue-manager

**Comment by Gustry** [comment]
Fix `industrial` -> `Industrial`

**Comment by fredychandra** [comment]
Hi @ismailsunni @Gustry & @Charlotte-Morgan @ivanbusthomi 

Here I try to incorporate ticket #3626 and #3947 with Land Cover Analysis feature value concept and its report. This concept feature might be relevant with elements at risk (assets) loss assessment establishment in the future. 

![lc_featurevalue](https://cloud.githubusercontent.com/assets/6345285/24735397/f152c41a-1aac-11e7-860e-da0765358c44.JPG)

If others type feature available from the data classification, eg. Crops: Kacang, Jagung, etc. We can make feature value as well because the attributes data are available on http://aplikasi.pertanian.go.id/bdsp/newlok.asp and https://bps.go.id/linkTabelStatis/view/id/1855

![lc_featurerate_formula](https://cloud.githubusercontent.com/assets/6345285/24735923/69c3d860-1aaf-11e7-97e5-70b3f355785a.JPG)


![keyword](https://cloud.githubusercontent.com/assets/6345285/24735958/988325f2-1aaf-11e7-9e88-deacd32de6e8.JPG)

**The Result (REPORT) :** 
Add approximate of potential loss on crops below estimated number of land cover affected by flood result (report).

![anlysis result](https://cloud.githubusercontent.com/assets/6345285/24736042/036a873e-1ab0-11e7-825c-ec0f35ac898b.JPG)

The calculating result of affected area of Padi field can be compared with total harvest area in one District (Certain area). It can get percentage of productive area that affected by flood (certain relevant hazard/event)

Happy to discuss.

**Comment by fredychandra** [comment]
Hi @ismailsunni  
Can you confirm this ticket is **ready** for InaSAFE 4.1 or InaSAFE 4.2, please? 
Thanks

**Comment by ismailsunni** [comment]
@fredychandra 
I am afraid that it will be on 4.2. I have been working on #4069 which more or less the same amount of work as this ticket.

**Comment by fredychandra** [comment]
Hi @ismailsunni 
Ok cool, I agree this work can be for InaSAFE 4.2

**Comment by ismailsunni** [comment]
Continuing this ticket, we will need three fields to be defined (specify) in the landcover.

| Field | Unit | Description |
| ----- | ---- | ----------- |
| Productivity | Kwintal / Ha | Used in productiviy  | 
| Producitvity cost | IDR/Ha | - | 
| Productivity value | IDR/Ha | - | 

Some questions
1. Should we manage for different unit? Or should we just ask the user to make sure their data using that unit? The cost and value  is in IDR, but I am sure we don't want the user from the other country to use IDR. I think we need to have option to set the default currency. Should we do the same for `Ha`?
2. We don't need a default value for these fields, do we? *just to confirm the requirement.
3. Since the field is in the feature level, we don't need to know the type of land cover, right? I will use an assumption that the value is correct for the feature.

I will put it in the field InaSAFE field step (like in the first image in @fredychandra 's comment above). We can tweak it later after I make the first working prototype.

cc @fredychandra @Charlotte-Morgan @timlinux

**Comment by fredychandra** [comment]
Hi @ismailsunni 

I think we can do it both whether set up the other units and request users set their data using the appropriate unit. This can make this analysis tools more universal and flexible. For the second question, I don't think we need set the default value since the productivity values will change over time (dynamic data) depending on the governmental (agriculture data) release each year or in the certain period.

**Comment by Charlotte-Morgan** [comment]
@fredychandra - in the sprint planning meeting; we will start on this for 4.2 but expect to finish it well in 4.3. We expect it to take time and need some work for polishing

**Comment by Charlotte-Morgan** [comment]
@fredychandra - can you please update this ticket with the discussion you had with @ismailsunni

**Comment by ismailsunni** [comment]
@Charlotte-Morgan 
The short summary of the discussion: @ismailsunni will implement the basic feature first (adding 3 more extra fields for productivity, prod cost, and prod value). For the initial version, it will use static unit and currency. We can make it adjustable if we have agree on the workflow.

I will need to show it in the report also. CC @myarjunar

**Comment by mbernasocchi** [comment]
@ismailsunni from my point of view, definitely not IDR. I'd rather have the value being "monetary" than a foreign currency. regarding Ha, I think it is ok to have it static for now.

**Comment by mbernasocchi** [comment]
@ismailsunni what do you think about having a classification that allows having all the existing keys to be a class?
let's say in my data I have:

- unidentified forest
- Coconut trees
- unidentified forest
- unidentified forest
- Coconut trees
- Coconut trees
- Coconut trees
- grassland

and in the report I automatically have:
- unidentified forest ....
- Coconut trees ......
- grassland  .......

**Comment by ismailsunni** [comment]
@mbernasocchi no worries, the released version will have the adjustable currency. My comment above only tell about the step

For the classification, yes we can do it. But, in the current InaSAFE, we have already make a value mapping like we do in the building and road. So it will be grouped by the class. Or this is not what you want?

**Comment by mbernasocchi** [comment]
@ismailsunni regarding the classification I was wondering if it is still possible to _not_ group by class (as it was in inasafe 2.x (?)).
so basically the classification is fully data driven

**Comment by Gustry** [comment]
For now in inasafe v4, only census data (population vector) can be a continuous exposure (no InaSAFE classification in the keyword wizard). All other exposure data have to be classified in InaSAFE using our internal classification. I will think about it.

**Comment by ismailsunni** [comment]
@mbernasocchi 
Is it possible ? Yes.
But, then we will have two grouping (group by internal class and group by the data). We need to decide how the user can specify which grouping that he want to use. Or we can put both of the in the report.

**Comment by mbernasocchi** [comment]
@ismailsunni maybe we can add an item to the classifications selection wizard called "classify using data values" or so and skip the next step
![image](https://user-images.githubusercontent.com/233663/27363528-373b71f8-5689-11e7-819e-08cffd93fe3e.png)

what do you think?

**Comment by ismailsunni** [comment]
@mbernasocchi Ah, that can work. We can also use it for the other exposure (if applicable)

**Comment by mbernasocchi** [comment]
yes, I think too. what do you think @Gustry ?

**Comment by mbernasocchi** [comment]
I wonder if we could just do it in the classifications file

**Comment by myarjunar** [comment]
Hi mas @fredychandra, I think I will separate the `productivity` specific information to its own table. It would be something like this:  

![selection_110](https://user-images.githubusercontent.com/11134669/28439846-e996f682-6dcd-11e7-8320-539985cfeca0.png)

I separate the `productivity` specific information from the analysis table because I think it would be irrelevant with the table title if we put the productivity data there, IMHO. What do you think?

**Comment by fredychandra** [comment]
Hi @myarjunar ...

It looks good, I agree to separate the information and like the shape/table you present the land cover analysis. This should relevant only for crops related field such as farm, corn, etc.  If we put whole land cover type there, it can create be a mis-leading information for the user/reader. Take e.g Residential have no productivity with Quintal unit, production cost as well as production value. In addition, I think we need to present the potential loss result on that table. I suggest just add one more collom on the left side. 

Regards,

**Comment by ismailsunni** [comment]
Hi @fredychandra 
Yes, I agree we shouldn't put the unrelevant land cover in the report. But just bear in mind, that the data that I use above is a dummy one. I am sure, the real data of land cover should only contains that crop related. (or, may be I am wrong here).

If there is a dataset that mix between crop related and not crop related, there are some alternatives to address it:
1. Ask the user to clean the data first. So, we will only have crop related. It's very easy to do.
2. If the user doesn't want to clean the data, the attribute of productivity in the non-crop related (e.g. residential) should be 0. Otherwise, the data doesn't make sense. Bad input will give bad output. So, we should make sure that they set it to 0.
3. We can make another step in the wizard that let user to select which land cover type that they want to show in the report. But it will need to create new property in the metadata and make the wizard longer / more complex.

So, I prefer to address it like point 1 or 2. If the data is reflecting real data, it shouldn't have non-crop related. If there is a data that contains both crop and non-crop, it should be not a common case. So, addressing the problem with point 3 is overkill.

**Comment by Gustry** [comment]
> 3. We can make another step in the wizard that let user to select which land cover type that they want to show in the report. But it will need to create new property in the metadata and make the wizard longer / more complex.

No need for a new panel, we can add easily a new group in the exposure classification 'Do not report'. It's different behaviour with  the `Other` group. We will discard this group in the `prepare layer` step.

**Comment by ismailsunni** [comment]
@Gustry ah yes, that's good idea that we can also implement. Less complex than my 3rd idea :)

But, still, I am not really sure we need to implement that unless we have real data that's mixed.

**Comment by Charlotte-Morgan** [comment]
Hi @fredychandra @ismailsunni @Gustry @myarjunar @mbernasocchi @samnawi 
apologies for rejoining this conversation again so late in the development.
I like what i see here and the option for data driven classification. 

I wonder too if there is room for a new "productive landcover" classification which would include only those land covers types for which it is relevant to expect values and to calculate the report for productivity, production cost and production values. 

Ie if the exposure is not either data driven or classified 'productive landcover' maybe the report should not be written.  I think this might address the issue of land cover elements being included in the report when they will never have  a productivity status.

**Comment by ismailsunni** [comment]
I think we can close this as it has been implemented in 4.2
