### ISSUE TITLE
Map template sawcuts

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3693]
We now have new report template for InaSAFE version 4.0 with many new features to address reporting standards - thanks to @ivanbusthomi and @lucernae 

# sawcuts
There are some changes required to the template to make it really happy.
- [x] the legend is very complete with label, threshold and counts. I think we might need to reduce the font size of both the title (12) and the labels (10) to give space to include units. Also move the legend up an to the left within the legend area on the page. Note: on portrait versions the legend is over flowing into the disclaimer area.
- [x] logo needs to be resized to match the width of the disclaimer block
- [x] analysis information is a great addition; maybe reduce font size (7) to the same as the disclaimer and try to avoid Software Version and Spatial Reference spilling to two lines
- [x] please check legends against standards; not exposed should not be included for population or land cover as it covers most of the map :(

**Comment by Gustry** [comment]
> please check legends against standards; not exposed should not be included for population or land cover as it covers most of the map 🙁

This should be fixed in PR https://github.com/inasafe/inasafe/pull/3702
`Not exposed` is disabled in the legend for landcover and population exposure. You still find it in the attribute table.

**Comment by timlinux** [comment]
+1 for introducing the concept of sawcuts where papercuts do not cut it :-)

**Comment by ivanbusthomi** [comment]
Hi @lucernae ,
I've made some changes in both the portrait and landscape template files. Here are the changes:
* Make `InaSAFE Supporters` text in the supporters logo properly centered
![image](https://cloud.githubusercontent.com/assets/7351977/22359857/89c29e7a-e47d-11e6-8a67-6d2fe31544d4.png)
* Make a few adjustment on legend font and placement
![image](https://files.gitter.im/ivanbusthomi/zsP8/blob)
* Adjust analysis information section so that it can contain more Data Source information. 
![image](https://cloud.githubusercontent.com/assets/7351977/22360126/a42a580a-e47f-11e6-94bc-6dc71a0ac2b0.png)
Related to this, could you please change the string `Software Version` to `Software`; and `Spatial Reference` to `Reference`? I prefer it to be just one line, or do you have any other preference?

This is the zip file that contains the templates and updated logo. Feel free to give suggestion.
[template_update.zip](https://github.com/inasafe/inasafe/files/734389/template_update.zip)

**Comment by lucernae** [comment]
Fix for this already merged
