### ISSUE TITLE
IFCW should filter available IF combinations when in non dev mode

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3823]
### Problem

![screen shot 2017-02-13 at 11 30 56 am](https://cloud.githubusercontent.com/assets/178003/22877831/eada4fc2-f1df-11e6-83a2-d2ae834ac7ba.png)

Cyclone : Only structures
Earthquake: no roads / landcover

@Charlotte-Morgan please give any further feedback as to which should be disabled

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution

**Comment by Gustry** [comment]
What about using the dock ?
@ismailsunni Is the KW wizard also limited (not able to set roads in the hazard keywords) when we are not in dev mode ? But what a layer with valid keywords but not in dev mode ?

**Comment by timlinux** [comment]
@Gustry I think we can assume @Charlotte-Morgan wants the dock filtered too...Again keeping the dev mode behaviour would be good.

**Comment by Gustry** [comment]
So we need to disable these combinations in the keyword wizard too.
I don't think I will do something to the dock as we shouldn't get layers compatible for these IF. (only and only if the layer keywords have been generated with developer mode and then if we use the dock not in developer mode)

**Comment by Charlotte-Morgan** [comment]
Agree - is an analysis should not be run then it should be disabled in all places for users. However, it is important to have access to all combinations in debug mode to test things and to ensure notes and documentation are complete.
Why do we want to disable things: simply because there is no use case yet or the analysis is 'silly' . This applies to the volcanic ash and I will endeavour to update notes and explain this very soon.
