### ISSUE TITLE
EQ Impact function in IF and KW Wizards

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3853]
### Expected Behaviour

We need to enable in the KW Wizard : 
* EQ Vector on Roads
* EQ Vector on Population
* EQ Vector on Structures
* EQ Raster on Roads
* EQ Raster on Structures

We don't want EQ Raster on Population Raster, as it's hard coded in the Earthquake function.

In the IF Wizard : 
* We want all of them.

For EQ Raster on Population Raster keywords, I would appreciate if you can still put the default EQ classification in `thresholds`.

**Comment by timlinux** [comment]
Also please take note of @Charlotte-Morgan 's request:

> I think the easiest thing to do is leave it as is and add a note in the code to say the displacement rate is not from the fragility curve

So add to the notes for EQ the following line: 

"Displacement rates calculated for Earthquakes are not derived from fragility curves. A nominal rate of 100% for MMI levels greater than 5 is used."

**Comment by timlinux** [comment]
Summary of actions needed for EQ:

1) Add the note for EQ as described above
2) Move the logic for defining displacement rates out of earthquake.py and enable it in hazard_classifications.py so that displacements are defined consistently for all hazards. (we will keep the same rates as we currently have > 5mmi = 100%)
3) We will disable editing of exposure thresholds in KW wizard for EQ for population (since they are defined by the fragility curve)
4) We will remove exposure threshold editing in KW wizard for EQ for only structures, others will be remove from the page

**Comment by Charlotte-Morgan** [comment]
+ 1 for note to track source of displacement rate

**Comment by Charlotte-Morgan** [comment]
I added a note in #3850

**Comment by ismailsunni** [comment]
Hi @timlinux 

> We will disable editing of exposure thresholds in KW wizard for EQ for population (since they are defined by the fragility curve)

Is it for both raster and vector EQ ? I saw @Gustry 's comment, EQ Vector should be enabled in the KW Wizard.

> We will remove exposure threshold editing in KW wizard for EQ for only structures, others will be remove from the page

Does it means only structure that shown in the KW wizard? In @Gustry 's comment above, road also needs to be shown.

Hi @Gustry 
> For EQ Raster on Population Raster keywords, I would appreciate if you can still put the default EQ classification in thresholds.

What about classified EQ Raster on Population? Should I also hard code the value maps?
