### ISSUE TITLE
Failed to Save Scenario

### ISSUE THREAD

**Issue by uswatunkh21** [inasafe/inasafe#3895]
### Problem
Failed to Save Scenario for all scenario without aggregation feature

```
2017-02-20T16:25:10	1	Traceback (most recent call last):
			  File "C:/Users/elida/.qgis2/python/plugins\inasafe\safe\plugin.py", line 869, in save_scenario
			    dialog.save_scenario()
			  File "C:/Users/elida/.qgis2/python/plugins\inasafe\safe\gui\tools\save_scenario.py", line 124, in save_scenario
			    self.dock.extent.crs)
			  File "C:/Users/elida/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 80, in extent_to_array
			    transformed_extent = transform.transformBoundingBox(extent)
			TypeError: QgsCoordinateTransform.transformBoundingBox(QgsRectangle, QgsCoordinateTransform.TransformDirection direction=QgsCoordinateTransform.ForwardTransform, bool handle180Crossover=False): argument 1 has unexpected type 'QgsGeometry'
			
2017-02-20T16:26:04	1	Traceback (most recent call last):
			  File "C:/Users/elida/.qgis2/python/plugins\inasafe\safe\plugin.py", line 869, in save_scenario
			    dialog.save_scenario()
			  File "C:/Users/elida/.qgis2/python/plugins\inasafe\safe\gui\tools\save_scenario.py", line 124, in save_scenario
			    self.dock.extent.crs)
			  File "C:/Users/elida/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 80, in extent_to_array
			    transformed_extent = transform.transformBoundingBox(extent)
			TypeError: QgsCoordinateTransform.transformBoundingBox(QgsRectangle, QgsCoordinateTransform.TransformDirection direction=QgsCoordinateTransform.ForwardTransform, bool handle180Crossover=False): argument 1 has unexpected type 'QgsGeometry'
		
```

### Expected Behaviour
Save Scenario can work well

### Environment
* InaSAFE : 4.0 
* QGIS : 2.14.8
* OS : Windows 10
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Java_Population_WGS84.tif
  * Hazard : Jakarta_Flood_18113_WGS84.shp (also happen when I use Jakarta_Flood_HKV_WGS84.tif)

**Comment by Gustry** [comment]
Thanks for the ticket @uswatunkh21 
@myarjunar Can you have a look to this ticket ?

**Comment by myarjunar** [comment]
Thanks @uswatunkh21 
> Failed to Save Scenario for all scenario without aggregation feature

I couldn't replicate the error with this description. It would be nice if you could give me the dataset that produced this error.

**Comment by Gustry** [comment]
I can replicate @myarjunar.
I used the gisv4 project in the test directory. But I don't think it's related to the data itself.
The error comes from save_scenario, because the extent is a now QgsGeometry in V4. Before we used a QgsRectangle, that's why it's failing. We need to transform the QgsGeometry to a QgsRectangle.

BTW, I think we should save in the exposure CRS now.

**Comment by myarjunar** [comment]
@Gustry I really couldn't replicate it, I tried all layers in the project and it works fine. And I also tried to transform the extent to QgsRectangle and it gives the exact same extent. So, do we still need to transform it to QgsRectangle?

**Comment by Gustry** [comment]
It should be fixed in the PR above.

@myarjunar It was not related to layers. This bug happens on every dataset if the user is using a requested extent, so it means : 
* no aggregation layer
* and checkbox 2 or 3 or 4 (when the user is selecting the requested area).
![screen shot 2017-02-23 at 18 42 28](https://cloud.githubusercontent.com/assets/1609292/23271498/e6b21536-f9f7-11e6-90be-25c7564c1600.png)

**Comment by myarjunar** [comment]
@Gustry ah.. I see. I look at your code and that's exactly what I did (`boundingBox()`). I was not sure before because I couldn't replicate the problem. So, I didn't know if it fix the problem. :sweat_smile:   Cool.
