### ISSUE TITLE
Infographics behaviour

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3934]
### Problem

Right now we had this kind of infographics:

<img width="1066" alt="screen shot 2017-02-23 at 16 18 19" src="https://cloud.githubusercontent.com/assets/831865/23252542/c7cfaafc-f9e3-11e6-86c7-26fe44c43287.png">

We had some behaviour that needs to be clarified:
Affected or displaced?
- Pie chart is showing total population affected for each hazard zone (perhaps change it to displaced?)
- Number of people in People section is total affected population (perhaps change it to displaced?)
- Vulnerability showed "from x people affected" (perhaps change it to displaced?)

Is the rounding behaviour as expected?
- All numbers in hazard zones in pie chart are rounded. But since pie chart needs to be total 100%. Total numbers in center of pie chart will be different than the number in People section.
- All the percentage in Vulnerabilities section might be different from the actual ratio used to calculate them, because of rounding.

Icons?
- What to show if user chooses minimum needs profile other than default BNPB_en. Some icons in minimum needs will be missing.

**Comment by felix-yew** [comment]
Hi, mas @lucernae - maybe I can add some suggestion about the:
> Affected or displaced?
> * Pie chart is showing total population affected for each hazard zone (perhaps change it to displaced?)

Maybe we still show the total population in pie chart (Affected + Not Affected + Not Exposed)

> * Number of people in People section is total affected population (perhaps change it to displaced?)

In the people section we can add the new icon and information for displaced, maybe we can add in the right side of affected icon. I think the number of displaced is the key to the vulnerability and minimum needs section (cmiiw).

![image](https://cloud.githubusercontent.com/assets/13621886/23257431/59969eb6-f9f6-11e6-926d-7fe7b89fee6a.png)

> * Vulnerability showed "from x people affected" (perhaps change it to displaced?)

After we have the number of displaced, so the vulnerability section will show "from x people displaced". 
![image](https://cloud.githubusercontent.com/assets/13621886/23257501/b89b0ffa-f9f6-11e6-9413-81249d012bb0.png)

> Is the rounding behaviour as expected?
> All numbers in hazard zones in pie chart are rounded. But since pie chart needs to be total 100%. Total numbers in center of pie chart will be different than the number in People section.

I think this number will be different because in people section we will take the number of affected and displaced. But, in total numbers in the center of pie chart will be the total of "Affected + Not Affected + Not Exposed"

> * All the percentage in Vulnerabilities section might be different from the actual ratio used to calculate them, because of rounding.

As long as it represent the results I think it is fine.

> Icons?
> What to show if user chooses minimum needs profile other than default BNPB_en. Some icons in minimum needs will be missing.

Yes, because in the first time we decide to use the BNPB_en as the minimum needs profile. Maybe if the user want to use the Sphere or other profile, some of them maybe use the same icons but we need to add the other icons to support the other profile. We need to discuss it later.

@Charlotte-Morgan - What do you think about my suggestion?

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - I like your suggestions above, especially the affected to displaced is nice.
For now I think we should not add new requirements. ie this report is only produced for BNPB min needs profile.

**Comment by Charlotte-Morgan** [comment]
I have some more thoughts:
Maybe the donut could show the number of people exposed to each hazard zone (regardless of affected) with the total exposed population.
Then the people affected can say which hazard zones or classes they are in.
It would be good to separate age from gender from vulnerability.
This report must include an acknowledgement of the source of the icons. Source: OCHA

maybe also look at this site to save us having to prepare all the svg
https://github.com/mapaction/ocha-humanitarian-icons-for-gis

**Comment by felix-yew** [comment]
Hi, @Charlotte-Morgan - thank you for your feedback
> For now I think we should not add new requirements. ie this report is only produced for BNPB min needs profile.

I agree

> I have some more thoughts:
Maybe the donut could show the number of people exposed to each hazard zone (regardless of affected) with the total exposed population.
Then the people affected can say which hazard zones or classes they are in.

Yes I agree, I think it will more help to explain each section in the infographic, too

> It would be good to separate age from gender from vulnerability.

Maybe in this section we can create two groups, ie gender and age group. Just for suggestion:
![separate the vulnerability](https://cloud.githubusercontent.com/assets/13621886/23451830/4438ec98-fe94-11e6-9df0-150c7530937a.png)

> This report must include an acknowledgement of the source of the icons. Source: OCHA

Yes, we need to add this icons source maybe in the middle of (footer) marginalia. Mas @lucernae, can we add this source text?
![image](https://cloud.githubusercontent.com/assets/13621886/23451960/d3efc29e-fe94-11e6-8a8b-c95a36ad7cea.png)

**Comment by lucernae** [comment]
For the text, for future reference, you can even change it yourself in this definitions file:
https://github.com/inasafe/inasafe/blob/develop/safe/definitions/reports/components.py#L465

All of the text in the report can be customized in that file. So later if you feel you want to change just the text, you can go there.

**Comment by timlinux** [comment]
Please remove the bracket so 1321321*) becomes 1232132*
