### ISSUE TITLE
UNDO: rounding on infrastructure report

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4062]
### problem ###
This is a ticket to request that a previous feature request is reversed :)
When I run InaSAFE analysis on infrastructure, the results are rounded (as per user requirements). However; if I have only 1 nuclear power plant in the hazard area it can be alarming for users to see results suggesting that there are 10 nuclear power plants in the hazard area.

### proposed solution ###
that we modify the rounding applied to buildings, roads and infrastructure to ensure that small numbers are not rounded in a way to mislead users.

Open to suggestions: but maybe we could round values greater than 1000 but use analysis estimates for values less than 1000.

@timlinux @Gustry @ivanbusthomi @samnawi @felix-yew - any suggestions?

**Comment by samnawi** [comment]
Yeah @Charlotte-Morgan I agree to undo the rounding process on infrastructure report. Because for some reason, the number of infrastructures affected will influence the decision of the action plan. 

Also, like in the case when we have 3 infrastructures in 3 different class, it will be reported as 10 infrastructures affected per hazard zone, then if we doing calculation total affected for each hazard zone, it will generate 30 infrastructures affected for all of the hazard class.

**Comment by Charlotte-Morgan** [comment]
hi @Gustry - is it possible to progress this work this week?

**Comment by Gustry** [comment]
Sorry, this was not finished.
@myarjunar Can you take it for the reporting side? (check my PR)

**Comment by Charlotte-Morgan** [comment]
@myarjunar - can we close this?
