### ISSUE TITLE
Could you bring back the old way to generate and style the map?

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#4240]
### Problem

Currently in InaSAFE 4.0 and 4.1, all of the reports that user get from InaSAFE analysis process are stored in temp folder. Based on users experience & feedback from several training that we had in April, they confused to find where is temp folder for all InaSAFE analysis process. Although this can be solved by changing your Location for InaSAFE analysis results in InaSAFE options (which we found this solution later).

Another thing is the features where the user can style their own map before click Print button in InaSAFE dock. There was a user who already had QGIS and InaSAFE training a long time ago and joined again in our training in April. He asked to us about the old way to style the map before click Print button and to freely choose the InaSAFE theme and orientation for their maps. This problem also can be solve by open the tmp folder to find .qpt files and try to style it in the QGIS Map Composer. But IMO, if the user is new to GIS and they not learn how to use map composer yet or they just learn how to style a map, it will be take time for them to produce a map based on what they want to show in PDF map.

Sorry to put this issue late but if this possible to you guys, could you bring back again the old way to generate and style the reports? Thanks!

### Expected Behaviour
The user can style their layers first and put what they want to show before click Print button in InaSAFE dock.

When the user click Print button in InaSAFE dock, they can choose the paper's orientation and select their own folder to put all the reports in.

### Environment
* InaSAFE : 4.0 & 4.1
* QGIS : 2.14.15
* OS :  ubuntu, windows 10
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent :

**Comment by Gustry** [comment]
Hi @adissadis,

This is still in our roadmap to bring back this feature. We are thinking about some nice things about reporting. I hope we will work on that for 4.2.

**Comment by adissadis** [comment]
Hi @Gustry,
Thanks for your information! Looking forward to get this features back to InaSAFE. :smile:

**Comment by Charlotte-Morgan** [comment]
hi @adissadis - agree, this is an important thing for us to address. However the work around is to share the *.qpt for users in the short term.

**Comment by timlinux** [comment]
I'm thinking maybe a good workaround for this would be allow the user to mask the standard templates by placing their customized versions (with the same names as the package delivered ones) in their .qgis2/inasafe/ directory.

This way when InaSAFE scans for the template it will first look in the user directory, then in the InaSAFE plugin directory.

**Comment by ismailsunni** [comment]
Hi @timlinux 
I just go back in time to see what's the old way of using custom template.
When the user click the print  button, we should show dialog to allow the user choose the template that he wants to use, like in the screenshot below:
<img width="918" alt="screen shot 2017-07-03 at 14 42 37" src="https://user-images.githubusercontent.com/1421861/27782936-82dce3ca-5ffe-11e7-9428-9cde83e95a52.png">

So, we need to create this dialog also to implement your workaround (to let the user choose which template he want to use)

**Comment by Gustry** [comment]
@ismailsunni What @timlinux meant is to first check in the '.qgis2/inasafe' directory if there is the same template (same name), if yes, use this one, if no, use the normal one that we are already providing. No new window (we want this feature in 4.1). It's just a quick workaround to overpass this missing functionality.

**Comment by ismailsunni** [comment]
Hi @timlinux 
After I dig deeper, it's not simple to do that. Firstly, the report is generated right after the analysis is finished. The reason is we need to get the current IF object's state to generate the report (to avoid this, we need to make the IF serializable). Because of that, even we have changed the template, we will still get the same map report for the analysis that have been run before changing the template.

I also found that we don't have this scanning mechanism to get the template. We simply define it (you can check in the `components.py`, in `report_a4_blue` dictionary).

For this tickets, we think we have two alternatives:
1. Set the template in the InaSAFE options. This will make us able to set the template path on the fly. Then we can use the selected template to generate the report.
2. @myarjunar 's idea: make a dialog pop up in the middle of analysis (after the IF finished) to choose the template. But it seems it's not pretty (at least for us).

If it's ok, I will go for 1st alternative.


Note:
The print button is not generating map / report. It's only retrieve the path for the report and map based on the current impact layer.

**Comment by ismailsunni** [comment]
@Gustry ah sorry, my tab didn't auto-refresh. I didn't see your comment. I will try to do it. It should be simple although I think I have an edge case which makes the print button won't work. Anyway, I will try to do it.

**Comment by Gustry** [comment]
@myarjunar Can you do that with the new infographics template?
This has been done in 4.1 about the map report.

**Comment by myarjunar** [comment]
@Gustry I already did in my last PR :wink:

**Comment by Gustry** [comment]
Ah thanks! Which one? Better to link PR with tickets

**Comment by timlinux** [comment]
In 4.2 we are adding support for QPT overrides in the user directory and we have added project variables for the things that we used to rely on the impact function instance to provide. In 4.3 we can try to bring back the chooser dialog...
