### ISSUE TITLE
Feature: Templating review in InaSAFE

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4303]
### Problem

We need a more flexible printing system in InaSAFE. I've been thinking about this a lot and here is what I propose:

1) **Support atlas prints**: Currently we can use an atlas map layout but the call to generate the atlas is different to the print call from a non atlas map.

**Outcome:** When the user has created a template that has atlas enabled, we should render the atlas to PDF.

2) **We need a system for dynamically changing the datasources in a composition**: We want to do infographics etc. from the composer, but we need to be able to reference specific tables in the map project which we will not know at design time.

**Outcome:** If a user references an InaSAFE impact layer, in their template, the reference should be maintained based on the current impact function outputs.

3_ **We need a system to reference specific templates based on the combination of hazard and exposure**: When a user is doing e.g. flood on population, he or she should be able to use a template (which e.g. includes infographic elements) specific to that hazard and exposure combination. We should have a fall back that if no specific template is defined for the hazard / exposure combination, it uses our default template (e.g. like the current A4 template we have).

**Outcome:** Reports are produced with contextual awareness of the hazard and exposure data.

4. **We need to rename the default template:** Lets use rather a generic name like "inasafe-generic-template.gpt"

**Outcome:** the template name will still be applicable regardless of color scheme or page size.

5. **We should just produce one map.** This one is more debatable, but why do we produce two maps  I think one is enough. @Charlotte-Morgan and team to comment on that.

**Outcome:** More ready to understand outputs

6. **We should support use of QGIS variables.** This can be a simple way to override aspects of the map e.g. the accent color without doing any template editing or programming.

**Outcome:** We have a way to make quick tweaks to the map.

CC @Charlotte-Morgan @ismailsunni @myarjunar

**Comment by lucernae** [comment]
@timlinux I'm also interested to see where the discussion goes.
Is it going to be implemented by improving our current report package or creating another one?
If it is still using current report system, I might be able to share some comments.
It also might help us with GeoSAFE.

1. I'm still not familiar with atlas. Perhaps we only need a code branching to invoke atlas print?

2. This operation is not natively supported in QGIS Composer. So, I propose that the reference be made using Jinja2 syntax? For example, let's suppose we had an HTMLFrame element in composer, then we want to put a table on that. Just put ```{{ impact_layer.html_table_we_want_to_show }}``` or it could be any report component that is already rendered as html string. We can pass the context easily to jinja2 renderer. I already made the current report system with this intention in mind if we need it. So we can extend the functionality.

3. We should define the valid combination in report metadata. So whatever function that tries to find a list of available templates can just filter based on report metadata definition. This makes it pretty easy too for me to use in GeoSAFE. I can compare with only metadata.

4. This should be straightforward. So no comments in mind.

5. Not my place to comment. But supporting one or more map from technical side have little difference.

6. The order of execution should be jinja2 template first, then QGIS Composer. So, we can achieve this by putting QGIS variable/expression just directly in the jinja2 template (if you need it to be applicable in template). Otherwise, just use it like a regular composer editing. We should be able to do this already, shouldn't it? I should try to give a proof of concept.

**Comment by timlinux** [comment]
@lucernae thanks for your comments, inline replies below:


>1.  I'm still not familiar with atlas. Perhaps we only need a code branching to invoke atlas print?

Yes we just need a small conditional that checks if atlas is enabled in the QPT and if it does, uses the atlas SVG generator, if not continue with the 'normal way'.

>2.  This operation is not natively supported in QGIS Composer. So, I propose that the reference be made using Jinja2 syntax? For example, let's suppose we had an HTMLFrame element in composer, then we want to put a table on that. Just put {{ impact_layer.html_table_we_want_to_show }} or it could be any report component that is already rendered as html string. We can pass the context easily to jinja2 renderer. I already made the current report system with this intention in mind if we need it. So we can extend the functionality.

Interesting but I was thinking more in terms of using the composer table object type, not html frames. One of the object properties of QgsComposerTable *should* let you set the datasource, though looking at the API for QgsComposerTable I think we may miss that call - we would need to investigate a little further....

> 3. We should define the valid combination in report metadata. So whatever function that tries to find a list of available templates can just filter based on report metadata definition. This makes it pretty easy too for me to use in GeoSAFE. I can compare with only metadata.

Ok that sounds reasonable.

> 4. This should be straightforward. So no comments in mind.

OK good

> 5. Not my place to comment. But supporting one or more map from technical side have little difference.

Further to this, I was thinking that the user could include additional map templates that should be rendered in there home folder that do not follow the hazard-exposure naming convention and we just automatically process anything we find there. Perhaps it is better if we arrange them like:

```
~/.qgis2/inasafe/scenerio-specific-templates/flood-population.qpt
....
etc
```

For scenario specific ones and then

```
~/.qgis2/inasafe/general-templates/a0-portrait.qpt
....
etc
```

for generic ones which all get automatically printed (and shadow the built in ones if the template names match)

> 6. The order of execution should be jinja2 template first, then QGIS Composer. So, we can achieve this by putting QGIS variable/expression just directly in the jinja2 template (if you need it to be applicable in template). Otherwise, just use it like a regular composer editing. We should be able to do this already, shouldn't it? I should try to give a proof of concept.

Yes I would be interested to see a proof of concept. If I understand you right you are saying you think you can also resolve QGIS variables within the JINJA2 context so if I e.g. have an JINJA  element like this:

```
<p style="background={{ @inasafe-accent-colour }};">Hello world</p>
```

We could resolve this by looking up the associated QGIS variable and replacing in the the template? That would be really cool (though actually one step further than I was looking for in item 6 above.

**Comment by timlinux** [comment]
@myarjunar In terms of specific tasks for 4.2 please do these:

-[ ] Add support for printing when atlas is enabled
-[ ] Move all templates except a4 blue landscape QPT into a resources folder called 'examples' which we can use during training if needed or users can adapt to their own needs.
-[ ] Rename a4 landscape to simply 'inasafe-report'
-[ ] Ensure that of the user has an inasafe-report.qpt in their ```~/.qgis2/inasafe/``` folder it is used in preference to the one shipped with InaSAFE.
-[ ] Create a new resource folder called hazard-exposure
-[ ] Set up support for hazard-exposure style report naming by scanning the hazard-exposure folder and rendering any report found there that matches the current hazard exposure combination e.g. for a flood on roads scenario with these default and user templates:

InaSAFE resources folder:

```
hazard-exposure/flood-roads-report1.qpt
hazard-exposure/flood-roads-report2.qpt
hazard-exposure/flood-structure-report1.qpt
hazard-exposure/flood-places-report1.qpt
hazard-exposure/flood-landcover-report1.qpt
```

User resources folder:

```
hazard-exposure/flood-roads-report1.qpt
hazard-exposure/flood-roads-report3.qpt
```

We will expect 4 map reports to be rendered:

1. The default report : ```<inasafe resource dir>/inasafe-landscape-report```
2. The user overridden report 1: ```~/.qgis2/inasafe/hazard-exposure/flood-roads-report1.qpt```
3. The InaSAFE shipped report 2: ```<inasafe resource dir>/hazard-exposure/flood-roads-report2.qpt```
4. The user defined report 3: ```~/.qgis2/inasafe/hazard-exposure/flood-roads-report3.qpt```

-[ ] For @ismailsunni Please take all the provenance data we have currently going into the provenance report (and anything that is not) and implement some logic so that when the user selects an impact layer, the QGIS project variables created / updated to reflect the current analysis.

-[ ] @Gustry I would like you to spend max one hour seeing if we can easily add data binding control next to the table source in QgsComposer (targeted for version 3) - then we can set the active table in a project variable and have it automatically update when we change context.

CC @Charlotte-Morgan @ivanbusthomi I would like to push to get these changes (except the last time which is R&D) into 4.2 - they will allow us to train BNPB staff with the ability to completely customize the reports easily and on a hazard by hazard basis. Please comment if you have any reservations about this.

**Comment by ivanbusthomi** [comment]
Hi @timlinux , these are what I have in mind:
> Support atlas prints

I think this is a very good idea, we maybe need to add an option (maybe in the dock?) for the user to enable the atlas if the analysis involves an aggregation. What I am concern is do we need a separate template for the atlas that contains atlas related item (ie: page X of X, title that contains aggregation name, etc) or we can just make the default template that is adaptable (it will show the atlas related item only if the option to generate atlas is enabled). I think the first one is easier. :smile: 

> We need to rename the default template

I agree with this, it will make it easier to manage if we are going to implement more customizable template by user.

> We should just produce one map.

I am sorry, I am a bit behind in this. Does it refers to the landscape and portrait template of the map? If so, I personally don't mind having both portrait and landscape by default. Because for example if the general shape of the impact map is portrait, for me it will be more convenient to see it in a portrait templates, same goes with the landscape one.

> We should support use of QGIS variables.

This week I have a little bit chance to look at the tutorial of qgis variable and have a little play about it. In my opinion, this will help us make the composition more customizable.

**Comment by timlinux** [comment]
> I think this is a very good idea, we maybe need to add an option (maybe in the dock?) for the user to enable the atlas if the analysis involves an aggregation. What I am concern is do we need a separate template for the atlas that contains atlas related item (ie: page X of X, title that contains aggregation name, etc) or we can just make the default template that is adaptable (it will show the atlas related item only if the option to generate atlas is enabled). I think the first one is easier. 😄

I think we will probably need to have separate templates. Personally I prefer that the user does not need to choose anything in the dock - we just enable atlas if it is present in the template, and if not, print 'normally'. What about we provide two standard templates:

1. Report summary template (which includes a map page and an infographic page)
1. By-area breakdown template which includes a map page per aggregation area and and infographic page per aggregation area.

We could add an option to InaSAFE options to disable atlas prints globally maybe?

> I am sorry, I am a bit behind in this. Does it refers to the landscape and portrait template of the map? If so, I personally don't mind having both portrait and landscape by default. Because for example if the general shape of the impact map is portrait, for me it will be more convenient to see it in a portrait templates, same goes with the landscape one.

Yes that is a good use case for having both I guess - ok by me to keep two.

**Comment by Gustry** [comment]
> I would like you to spend max one hour seeing if we can easily add data binding control next to the table source in QgsComposer (targeted for version 3)

Very interresting to look at this! Unfortunetaly, there is not yet some data defined properties in the Attribute table widget. So to add one, like the source layer, I first need to understand how to implement the QgsExpressionContext in the attribute table widget etc. So it will take a little bit of time to understand this. But if someone is already familiar with these expressions context etc, it should be quick I think to add the source layer data defined by expression.

**Comment by timlinux** [comment]
Hi @Gustry 

Thanks for the update - maybe this is something you can look into during the hackfest in Nodebo?

@ismailsunni and @myarjunar can you check in and confirm you are on board with your tasks above (and taking @ivanbusthomi 's comments into account)?

**Comment by ismailsunni** [comment]
Hi @timlinux 
I will work on my task today.

**Comment by ismailsunni** [comment]
Hi @timlinux 

Since some of the provenances are not string, which one do you prefer?
1. Force converting to string. Number is easy. For another data type, I will use json representation. But if you want to retrieve the value, we will need to parse it.
2. Make a naming convention for the variable key. For example, for dictionary it will be something like: `dictionary_key__dictionary_key`: `value`. For list, may be the key will be: `list_key__1`, `list_key__2`, and so on. The more complex data type, the key naming will become more complex. And some of the provenance are complex. E.g. exposure_keywords, hazard_keywords both are complex dictionary.

I will implement the first solution first, since it's easier, and may be we don't need all of the provenance. 

I will also clean the variables if the user change the layer to non impact layer one.

**Comment by myarjunar** [comment]
Hi @timlinux , checked in. Will be my priorities for today.

**Comment by timlinux** [comment]
@ismailsunni

Referring to your question above, I think JSON would be difficult to work with in the context of an expression - at least for not so geeky users. I think we should take two approaches:

1. I like your key__key__key: value scheme that would be a good approach for when users want to access single values.

2. Where we want a result that resolves back to a table, I think we should return it as an html snippet so the user can include it in a label or html element as a complete table.

**Comment by ismailsunni** [comment]
Hi @timlinux 
Ok, I will implement the key__key__key: value.

> Where we want a result that resolves back to a table, I think we should return it as an html snippet so the user can include it in a label or html element as a complete table.

I think in the provenance, there is no html. So we don't need to handle it. Or may be I misunderstand your's comment?

**Comment by myarjunar** [comment]
Hi @timlinux , there is no available method from qgis api to extract atlas as PDF so I create the atlas renderer manualy. But I'm stuck in this problem, the atlas won't zoom to the extent of the aggregation feature, here is the example:

[a4-landscape-blue.pdf](https://github.com/inasafe/inasafe/files/1192742/a4-landscape-blue.pdf)

do we need to show the aggregation layer in the map canvas to get this working?

**Comment by myarjunar** [comment]
@timlinux I create a simple example of atlas printing and somehow I can solve my problem :sweat_smile: . Is this what you expecting with atlas printing?
[a4-landscape-blue.pdf](https://github.com/inasafe/inasafe/files/1194504/a4-landscape-blue.pdf)

**Comment by timlinux** [comment]
Yeah that look s good @myarjunar
