### ISSUE TITLE
Infographic Report bugs/suggestions

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4389]
### Problem
Minor bugs/suggestions with the Infographic Report

1. Not all colours appear in the doughnut legend and not all labels appear on the graph
![image](https://user-images.githubusercontent.com/10228025/29648545-1a895ff4-88d2-11e7-88ff-e8dd6acb81ca.png)

2. People displaced - Counts greater than a thousand have unit text which means counts less than a thousand look like they are missing unit text, and they should not have decimal points.  
I think the percentage text colour is too light. A division between the age and gender infographics would indicate that they are separate counts. 
![image](https://user-images.githubusercontent.com/10228025/29648787-61190fea-88d3-11e7-96d6-8f46b206d6c0.png)

3. I think there should be consistency in the definitions, symbology and text of Infant/<5y.o. and Elderly/>60y.o. 
![image](https://user-images.githubusercontent.com/10228025/29648989-be96196e-88d4-11e7-84e2-b1151cb9d70d.png)

### Proposed Solution
The doughnut legend and labels should be fixed, the others are just suggestions

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew can you please look at points 1 and 2 in this ticket.

**Comment by Charlotte-Morgan** [comment]
@lrpower - did you look at the demographic definitions for point 3. Maybe that will help. We have different definitions for age and vulnerbility.

**Comment by Charlotte-Morgan** [comment]
@lrpower - regarding your points about definitions. The age classes are not mutually exclusive but reflect some of the most common categories used in the humanitarian sector which does not have any good standards for us to follow.
Similarly, the overlap between age and vulnerability is apparent as you have pointed out.
We could add the definitions for the default classifications to the infographic but I chose not to because this allows the user to use the categories to meet their own needs.

**Comment by felix-yew** [comment]
Hi @lrpower -
> 1. Not all colours appear in the doughnut legend and not all labels appear on the graph
image 

In the design of infographic, I also put the labels in the chart, but somehow the result of infographic can not show the label in the certain space in chart. Maybe mas @myarjunar can explain better related to the chart and also about the colour appear in the legend.

> 2. People displaced - Counts greater than a thousand have unit text which means counts less than a thousand look like they are missing unit text, and they should not have decimal points.

Good point Lauren, if the people displaced less than a thousand, ie. in a hundred(s), it should appear `Hundred`. And, I think it is better if the number less than a hundred it will not use the unit text to make it easy to read or maybe I can add some disclaimer about not using the unit text if the result number less than a hundred. It will help to make the user understand about the result number in this section.

> I think the percentage text colour is too light. 

Okay, I will make it more easy to read.

> A division between the age and gender infographics would indicate that they are separate counts.

Yes, I will make a separator in this section. It is good since we using the qpt template for infographic :+1: 
This is the mock up for `People displaced by age and gender` section:
![image](https://user-images.githubusercontent.com/13621886/29699200-04b904f0-8985-11e7-9b57-af4fb73c0576.png)
What do you think for the percentage colour and the separator @lrpower @ivanbusthomi @myarjunar ?

**Comment by lrpower** [comment]
I agree it's not usual to use the unit word Hundred and Tens would look even weirder! It just confused me when I first saw it because I wasn't sure if it was 460 (four hundred and sixty) or if the thousands text was missing (four hundred and sixty thousand). Removing the decimal point for values less than a thousand would help.
And the percentage text and divider looks good!

**Comment by lrpower** [comment]
@Charlotte-Morgan so I can't find anything in the help doc clarifying if _Under 5: Persons aged under 5 years_ is 5 and under (0-5) or Under 5 (0-4). The demographic defaults are also both set to 0.9 (which I know can be changed) so are these the same or not? If _Under 5_ is 0-4 then that's the same as Infant and the symbols/definitions should reflect this. 
Side note... the help doc, demographic default options etc all reference a youth category which is not appearing in the Infographic report.

**Comment by felix-yew** [comment]
Hi @lrpower -
> I agree it's not usual to use the unit word Hundred and Tens would look even weirder! It just confused me when I first saw it because I wasn't sure if it was 460 (four hundred and sixty) or if the thousands text was missing (four hundred and sixty thousand). Removing the decimal point for values less than a thousand would help.

Sounds good, I will discuss with our team first.

> And the percentage text and divider looks good!

Thank you, okay we can use the colour.

**Comment by lrpower** [comment]
hey @felix-yew I've noticed hundred values still have decimal points. we have a PacSAFE workshop coming up, perhaps this can be assigned to @mbernasocchi?

**Comment by felix-yew** [comment]
Hi @lrpower - yes, I have try it in develop version and still find this issue. I agree with you to remove the decimal point for value less than a thousand and also keep the rounded. Mas @myarjunar what do you think about this?

**Comment by Charlotte-Morgan** [comment]
Hi @lrpower - please let us know when you have training events and if anything needs to be pushed to a bug fix release or back ported.

**Comment by lrpower** [comment]
funny you mention that @charlotte-morgan, Craig and I have a workshop in Tonga next week

**Comment by mbernasocchi** [comment]
Hi @lrpower I'm currently in honeymoon, that is why I missed the notice, do you want me to look into this later on (like during the pacific GIS conference if I'll be there)? Cheers

**Comment by lrpower** [comment]
@mbernasocchi this can wait, please enjoy your honeymoon! I'll see you at the conference!
