### ISSUE TITLE
We need to separate print() from the main IF run method

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4523]
See #4509 
Once the deserialisation is done, @myarjunar to implement print as a separate step from the analysis with the ability for user to first select a QPT before running print:

![screen shot 2017-10-16 at 09 33 41](https://user-images.githubusercontent.com/178003/31600360-6973ddf8-b256-11e7-9154-14b80d77de76.png)

**Comment by timlinux** [comment]
Will fix #4240

**Comment by myarjunar** [comment]
extra notes: "we want to also have the button that will open the print layout in composer instead of directly printing to pdf"

![screen-shot-2017-10-17-at-10 03 51](https://user-images.githubusercontent.com/11134669/31707664-244973ec-b417-11e7-8296-43daec3d692c.png)

**Comment by myarjunar** [comment]
@timlinux it turns out that we still need to generate report automatically after the IF analysis completed because we need to show the table report in the dock. So what's in mind is that we will use this new dialog only for the customization of the map report. Am I correct? Or is there another approach to handle this?

**Comment by Gustry** [comment]
@myarjunar What is missing in this ticket?
