### ISSUE TITLE
Wrong calculation for Landcover Enrich Report

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4566]
### Problem
In the last DRR Month, I show up an InaSAFE capability to analyze the landcover affected by hazard.
Apparently, there is a different result between InaSAFE and manual calculation (area of affected * productivity rate)

As we know, the keyword wizard requires unit in a hectare.
![image](https://user-images.githubusercontent.com/8871958/32161339-c2b43868-bd87-11e7-8b30-e2cb8692c01e.png)

Then, I try to replicate the calculation process, using a test data (attach in this ticket).

This is the result
![image](https://user-images.githubusercontent.com/8871958/32162111-6daad48c-bd8a-11e7-92d6-51f9517a328b.png)

If I see in the code
![image](https://user-images.githubusercontent.com/8871958/32162390-648baf4c-bd8b-11e7-8b82-1412121923d1.png)

Seems like the affected area (size) that shows in the attribute table was generated in hectares. 
But in the calculation formula, assume in sqm. So, it still needs to divide by 10000.

### Expected Behaviour
It has to calculate in the same unit

### Environment
* InaSAFE : Master and Develop
* QGIS : 4.14
* OS : Win 7 64 Bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
[Test_Data2.zip](https://github.com/inasafe/inasafe/files/1426578/Test_Data2.zip)

Checklist (if applicable): 
* [x] Did you try to run it in debug mode ?
* [x] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy

cc : @Charlotte-Morgan @timlinux @ismailsunni @Gustry @ivanbusthomi @felix-yew

**Comment by Gustry** [comment]
I confirm that InaSAFE is not computing hectares but only SQM by default.

BTW, I see that your attribute table is not vertically aligned. It means you are running an old version of QGIS and you can update ;-)

**Comment by samnawi** [comment]
Ok @Gustry I'll try this in newest version of QGIS

**Comment by Gustry** [comment]
I won't solve your issue, it was just a quick hint ;-)

@ismailsunni worked on that feature about productivity, so we may have some inputs.
I guess we need to fix the formula in InaSAFE

**Comment by ismailsunni** [comment]
Hi @samnawi 

Like @Gustry said, the unit of the size field is in meter square (sqm).

> Seems like the affected area (size) that shows in the attribute table was generated in hectares.

No, it's in meter square (sqm).

The formula in the calculation and your manual calculation is the same.

`productivity_rate (in 100kg/hectare) * size (in sqm) / 10000`

We already divide the number by 10000 (to convert the size from sqm to hectare.

So, I am not sure where is the issue, since everything looks right in the attribute table.

**Comment by ismailsunni** [comment]
Hi @Gustry 

After discussing with @samnawi this morning, I found out that the value in the attribute table is in hectare. There is already conversion inside the `SizeCalculator` class, in this line https://github.com/inasafe/inasafe/blob/develop/safe/gis/vector/tools.py#L401

The productivty post processor assumed that the size is in sqm, that's why I divide it by 10000.

I am not sure if it has conseuquent, but it seems changing the formula is the (hack/short) fix, doesn't it?
But, if someone adds use the same post processor (e.g. productivity_post_processor) in the other exposure, where the size is not in hectare, it will give wrong value also.

Ideally, we should put the size unit in the post processor parameter, so that we can do conversion.

Do you have any comment or suggestion?

<img width="476" alt="screen shot 2017-10-31 at 09 36 43" src="https://user-images.githubusercontent.com/1421861/32205541-659003a6-be22-11e7-8e68-e01636ebd7be.png">

**Comment by Gustry** [comment]
> There is already conversion inside the SizeCalculator class, in this line
Ah yes, the size calculator is smart now :)

> But, if someone adds use the same post processor (e.g. productivity_post_processor) in the other exposure, where the size is not in hectare, it will give wrong value also.

The other exposure has a different base unit, so it's fine, no?

**Comment by ismailsunni** [comment]
Yes, different base unit, but the same post processor (then same formula)

**Comment by Gustry** [comment]
Yes, but productivity is used only for landcover, so it's fine?

**Comment by ismailsunni** [comment]
Yes. That's why I call it as short fix. Anyway, let's close this first for now. Thanks.

**Comment by Gustry** [comment]
But I don't think we will have productivity for something else than landcover

**Comment by ismailsunni** [comment]
Yeah, I agree. It's possible (building productivity), but not applicable in real world. :)

**Comment by Charlotte-Morgan** [comment]
Well spotted @samnawi and thanks everyone for resolving this one

**Comment by samnawi** [comment]
Hi @ismailsunni @Gustry @Charlotte-Morgan Seems like it does not merge to release version. Is it will be applied in 4.3 version?

**Comment by ismailsunni** [comment]
It has been merged to 4.3 / develop.
It's not merged in 4.2.5, I missed to backport it before releasing it.
It has been merged to master branch, so it will be available in the 4.2.6 (if we ever release it)
