### ISSUE TITLE
Can Not Run Some Analysis in Developer Mode

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4585]
### Problem
In developer mode, we already set all combination of exposure and hazard as a valid combination. It's been done in the IF wizard when choosing the exposure and hazard. But, we can't run it. I can't run it also in dock.

<img width="1310" alt="screen shot 2017-11-07 at 08 55 33" src="https://user-images.githubusercontent.com/1421861/32473922-7b1bde1e-c39c-11e7-82e6-6445b10667fe.png">

### Expected Behaviour
We should able to run all combination in developer mode.

### Proposed Solution
I think we just need to put `if` and see the developer mode flag when validate the combination.

**Comment by Gustry** [comment]
Well, it depends on how we see the developer mode.

So let's say without developer mode, the user set all possible combinations hazard on exposure A and exposure B in his keywords. (Exposure C is not allowed).

Then the user toggles developer mode. What do you expect?
* To be able to set keywords on exposure C (because it was not enabled in the KW wizard before)?
* Or to be able to run this hazard on exposure C without running the KW wizard? (this is actually what you are trying to do, exposure C is not defined in your keywords). But the problem here, the impact function needs to create automatically what the user hasn't done in the KW wizard for the value map/thresholds. So what the impact function should create by default for value maps/thresholds? Based on definitions, I'm not sure it's the best because it's only default values. Developer mode is here to test new things.

Both have pros and cons:
* I'm in favor running the KW wizard to set keywords with the exposure C. Then the IF will run automatically.
* But, we update the keyword file. The impact function needs to check if the combination is allowed according to definitions if we are not in developer mode.

I would still go for option 1 and we can close this ticket. Run the KW wizard to set exposure C. What do you think?

**Comment by ismailsunni** [comment]
Ah yes, sorry, my bad. I didn't re-run the keywords wizard, and forget that I need to set the classification for place exposure. All is good now, I also prefer the first option :)

Sorry for the noise.
