### ISSUE TITLE
North arrow expression does not let the arrow render - shows a red cross instead

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#4714]
### Problem

Issue from @Charlotte-Morgan 

North arrow expression does not let the arrow render - shows a red cross instead

### Proposed solution
* Fix some old path
* Check expression

**Comment by ismailsunni** [comment]
I got this also when do the training

**Comment by ismailsunni** [comment]
Hi, the solution of this bug is make sure you set the north arrow in the option dialog. It was set to the wrong path. Most probably because we move the location of the resource image to another place, but we already store the old path in the setting, thus it will be used the next time we launch InaSAFE.

So, the solution is checking the path is correct.

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni 
I think it is happy now but am not sure anything has changed with my path and the file was always there.
I am happy to close this now

**Comment by Gustry** [comment]
I could confirm, we checked the path in the settings and the path the was right but the arrow couldn't be displayed again.

**Comment by ismailsunni** [comment]
If the path doesn't exist, just use default one
