### ISSUE TITLE
Metadata converter - window off the screen

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4732]
### Problem
The new InaSAFE Metadata Converter tool does not fit well on my screen and its not possible to resize or move.
```
Copy/paste some InaSAFE logs here if it was an error.
```

### Environment
* InaSAFE : 4.3
* QGIS : 2.18
* OS : Windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make the window smaller and centre on the screen.

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 

> The new InaSAFE Metadata Converter tool does not fit well on my screen 

Can you share some screenshot for it?

**Comment by Charlotte-Morgan** [comment]
Opens like this
![image](https://user-images.githubusercontent.com/5743135/33694970-01dbfdc0-db4f-11e7-8310-c778cfbbde52.png)

With a bit of fiddling can get this .. but no smaller
![image](https://user-images.githubusercontent.com/5743135/33695017-32f23a28-db4f-11e7-8168-5b4af2115faf.png)

**Comment by ismailsunni** [comment]
After looking around, this bug is from upstream (QT) related to wordWrap in QLabel.

This is a discussion in [Stack Overflow](https://stackoverflow.com/questions/25644026/setting-word-wrap-on-qlabel-breaks-size-constrains-for-the-window).
This is the bug report in QT: https://bugreports.qt.io/browse/QTBUG-37673
It has been fixed in QT 5.4, but QGIS 2.18 still uses QT 4.8.

I made a work around in #4748. It's not perfect, but I think it's more usable than without it.

Please check it if you had time @Charlotte-Morgan
