### ISSUE TITLE
The affected result show the different total number from estimated number per hazard zone

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4778]
### Problem
When I run flood raster vs population raster in develop version I find that the total number in affected result are different between total number from estimated number per hazard zone. See the image below
![image](https://user-images.githubusercontent.com/13621886/33929679-ea744b74-e01c-11e7-8425-b6e313c2e958.png)
I think the total number enter in wrong target. It should be in the affected total number but I see that the total number enter in not affected.

When I check in the Population Parameters in InaSAFE Option, the High and Medium explain that it checked.
![image](https://user-images.githubusercontent.com/13621886/33929456-293f502a-e01c-11e7-829e-5546a3bd839c.png)

### Expected Behaviour
The total number in affected result are correct.

### Environment
* InaSAFE : 4.3.0.dev-master
* QGIS : 2.18.14
* OS : Win 8/ 64bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : [Jakarta_population_inaRISK.zip](https://github.com/inasafe/inasafe/files/1554748/Jakarta_population_inaRISK.zip)
  * Hazard : [Jakarta_flood_HKV.zip](https://github.com/inasafe/inasafe/files/1554747/Jakarta_flood_HKV.zip)
  * Aggregation : -
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy :smile: 

@ismailsunni @Gustry @myarjunar @samnawi @ivanbusthomi @Charlotte-Morgan

**Comment by ismailsunni** [comment]
Investigation result:
1. The problem is caused by the population parameter doesn't show `Flood classes`, while the hazard use it for exposure population. Then it will take False as a default value. That's why all is un-affected.
2. The reason why the population parameter doesn't show the `Flood classes` is because it doesn't have `exposure` key that represente the supported exposure for the classification
3. My fix in #4778 will check if the supported exposure is empty, it means it will support all exposure
4. You need to restore default classification in population postprocessor to make it work.
