### ISSUE TITLE
Total Exposed in Population Analysis Report shows inappropriate number

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4810]
### Problem
Seems like the number of Total Exposed in Population analysis report didn't represent inappropriate number.
![image](https://user-images.githubusercontent.com/8871958/34100226-5d9a49dc-e414-11e7-870d-341f7aa70bed.png)

But, If I see in check the impact layer using Group Stats, seems like shows the right number 
![image](https://user-images.githubusercontent.com/8871958/34100554-6168fcc4-e415-11e7-898b-7a4fdac7f7a4.png)

==========================================================

I also find out in the other hazard
![image](https://user-images.githubusercontent.com/8871958/34100284-91f0b536-e414-11e7-87aa-9b51cf4955bc.png)

![image](https://user-images.githubusercontent.com/8871958/34100704-ead86904-e415-11e7-814a-ec78844a7608.png)

### Expected Behaviour
Total Exposed should be calculated from Very High, High, medium, Low, and Very low zone (present in hazard zone)

### Environment
* InaSAFE : Develop
* QGIS : 2.18.13
* OS : Win 7 64 bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : WorldPop
  * Hazard : Tsunami Padang and Ebulobo Hazard Zone 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy.

**Comment by myarjunar** [comment]
@samnawi tbh, I only take whatever appears in the analysis summary layer. We need to check if there are any calculation error for total exposed in analysis summary. cc @Gustry

**Comment by Gustry** [comment]
@myarjunar side note:
I don't have the "exposed note" like in @samnawi screenshots:

![screen shot 2017-12-21 at 10 09 49](https://user-images.githubusercontent.com/1609292/34248629-1cc958a6-e637-11e7-911e-1075c6d0c539.png)

I think it's not normal

**Comment by myarjunar** [comment]
@Gustry yes because the note is for population exposure, could you try it on pop exposure? thanks

**Comment by Gustry** [comment]
But some roads are exposed too, so why not for other exposure too? Sorry, maybe I'm tired ;D

**Comment by myarjunar** [comment]
it's `Exposed people` :smiley:  It was a request from Charlotte to have additional notes for population. I mean, could you try to check the calculation for pop exposure as well?

**Comment by Gustry** [comment]
Ok, I think I could spot the issue. It happens only for population exposure. (because before 4.3, calculations were computed the same way for all exposures and I was trying with roads and buildings, and these `not exposed` values are correct).

So correct me if I'm wrong @ismailsunni but the error is coming with the custom `Population parameters`.

This is what the postprocessor is returning, either: True, False or Not Exposed, marked as blue:
![f792c30c-efe6-11e6-9fe5-99711ce00b0e](https://user-images.githubusercontent.com/1609292/34304097-844a42cc-e738-11e7-9301-b18c9edce0de.png)

I added some notes in the docstring:
https://github.com/inasafe/inasafe/blob/develop/safe/processors/post_processor_functions.py#L177

But the first check, if it's population, then it will return only True or False, it will never return 'Not exposed' in `is_affected`. Can you have a look here? I guess we should just return 'not exposed' instead of always False, but I'm not sure.

I noticed that we have a redundant field, which must be the same value:
![screen shot 2017-12-22 at 17 04 47](https://user-images.githubusercontent.com/1609292/34304521-70d926d4-e73a-11e7-9229-f248593bbe98.png)

**Comment by ismailsunni** [comment]
Ah yes, I think you are right @Gustry. I only return True or False for the population. I will check next week.

**Comment by ismailsunni** [comment]
I have made a fix for this issue in #4833 
Can you test it @samnawi or @Gustry ?
