### ISSUE TITLE
UnboundLocalError in MultiExposure tools

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4855]
### Problem
When I tried running multiexposure tool, I received this error:
```
Report Generation issue
Failed to extract context

Problem
The following problem(s) were encountered whilst running the analysis.
UnboundLocalError

Details
These additional details were reported when the problem occurred.
local variable 'value_headers' referenced before assignment

Diagnostics
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\report\impact_report.py", line 728, in process_components context = _extractor_method(self, component)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\report\extractors\general_report.py", line 44, in general_report_extractor impact_report, component_metadata)
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\report\extractors\general_report.py", line 422, in multi_exposure_general_report_extractor 'value_labels': value_headers,
```

### Expected Behaviour
It should run without error

### Environment
* Tool: Multiexposure tool
* InaSAFE : develop
* QGIS : 2.18.12
* OS : Win 7 64

* Data used :
  * Exposure : [Place](https://github.com/inasafe/inasafe/files/1621901/Place.zip), [Population](https://github.com/inasafe/inasafe/files/1621902/Population.zip)

  * Hazard : [Earthquake](https://github.com/inasafe/inasafe/files/1621897/Earthquake.zip)

  * Aggregation : No
  * Extent : 
  
### Proposed Solution
Make it happy

CC @timlinux @Gustry @Charlotte-Morgan @myarjunar

**Comment by myarjunar** [comment]
so we have to figure out something here, the problem happens because the hazard has a different classification for place and population. For place, it uses generic hazard classification (high, medium, low), for population, it uses eq mmi scale (I, II, III, etc). when the hazard classification is same for all exposures used in the multi-exposure, we can easily show something like this in the report (see the first table):
https://user-images.githubusercontent.com/11134669/32420613-82730ea4-c2bf-11e7-8c67-11881e058aa5.png

but what is your suggestion on how the table will looks like when there are more than one hazard classification being used in the analysis ? cc: @ivanbusthomi @Gustry @ismailsunni @Charlotte-Morgan @timlinux

**Comment by Charlotte-Morgan** [comment]
Hi everyone
My expectation is that multi exposure analysis is replicating realtime functionality and that the hazard will be a single hazard with the same classification (or else it would be multi hazard too)
.... thinking music .....
this means we will probably want to limit the permissible combinations to those we use in realtime or to things that by default use the same classification.

for example tsunami impact on buildings and people might be a bad choice because the default thresholds for tsunami on buildings and people use different classifications

...... more thinking music ...
but then again, the hazard data allows you to set different classifications for different exposures so it should be fine 

/me heads off to test this

**Comment by Charlotte-Morgan** [comment]
I can replicate this error when i run maumere tsunami impact on people and buildings where there are 2 different hazard classifications.

```
Report Generation issue
Failed to extract context
Problem
The following problem(s) were encountered whilst running the analysis.

UnboundLocalError
Suggestion
You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details
These additional details were reported when the problem occurred.

local variable 'value_headers' referenced before assignment
Diagnostics

In file "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\report\impact_report.py", line 728, in process_components context = _extractor_method(self, component)
In file "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\report\extractors\general_report.py", line 44, in general_report_extractor impact_report, component_metadata)
In file "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\report\extractors\general_report.py", line 422, in multi_exposure_general_report_extractor 'value_labels': value_headers,
```

**Comment by Charlotte-Morgan** [comment]
@timlinux please look at this and consider
