### ISSUE TITLE
Needed Information for Realtime

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4857]
### Problem
To replicate realtime analysis, we need to provide some information to get richer report. I already made some of them, but I think we are still missing some of them. Here the list that I have made:

```python
earthquake_extra_keywords = [
    extra_keyword_earthquake_latitude,
    extra_keyword_earthquake_longitude,
    extra_keyword_earthquake_magnitude,
    extra_keyword_earthquake_depth,
    extra_keyword_earthquake_description,
    extra_keyword_earthquake_location,
    extra_keyword_earthquake_event_time,
    extra_keyword_time_zone,
    extra_keyword_earthquake_x_maximum,
    extra_keyword_earthquake_x_minimum,
    extra_keyword_earthquake_y_maximum,
    extra_keyword_earthquake_y_minimum,
]

ash_extra_keywords = [
    extra_keyword_volcano_name,
    extra_keyword_region,
    extra_keyword_eruption_height,
    extra_keyword_volcano_eruption_event_time,
    extra_keyword_volcano_alert_level,
    extra_keyword_time_zone,
    extra_keyword_volcano_latitude,
    extra_keyword_volcano_longitude,
]
```

There are some more:
- [x] Vent height for volcano https://github.com/inasafe/inasafe-realtime/issues/151#issuecomment-356172268 (get it from data, we should make it as an extra keywords)
- [ ] Shakemap ID for earthquake. Where can I get it @lucernae ?

Please add @ivanbusthomi @samnawi @felix-yew @lucernae

**Comment by lucernae** [comment]
@ismailsunni The parameter needed for hazard events:

Earthquake:
- All extra keywords you put in the issue + following extras.
- event_id/shake ID: from the grid.xml , which is event_time. But we have two kinds of shakemap. please refer to https://github.com/inasafe/inasafe-realtime/issues/60. I advise that this comes prefilled from grid.xml, but can be modified by user (if user convert grid.xml from InaSAFE desktop). Because we have 2 kinds of grid.xml and it might be unreliable to get the shake ID from the second one, because they mean different thing
- extra keywords to know the **source** of the EQ (so we can identify the type of grid.xml). In our terminologies, it can be **initial** or **post-processed/data-informed**. We have no reliable way to determine this from grid.xml. So, I advise we include it so user fill it from combo-box or text field when user convert the grid.xml

Ash:
- All extra keywords you put in the issue + following extras.
- Event ID, which is taken from YYYYMMDDHHmm[zoneoffset]_[volcano_name]. Example: 201712012200+0800_Agung. 
- If you have volcano data in InaSAFE desktop, you can nicely extract information from the intersected volcano, like vent_height, lat, long, and volcano name. Maybe the form need to mirror the form in Realtime

Flood:
- We also need Flood ID, but we have no standard for this. At the moment, I was using YYYYMMDDHH-6-rw as ID. Because it was always 6 hour interval in Jakarta.

**Comment by ismailsunni** [comment]
> If you have volcano data in InaSAFE desktop, you can nicely extract information from the intersected volcano, like vent_height, lat, long, and volcano name. Maybe the form need to mirror the form in Realtime

yes, this is also one of my polishing plan. I will keep the custom user input to support volcano that doesn't included in the volcano data.

It seems I need to tweak shakemap converter and the wizard again.

I will try to do it tomorrow.

**Comment by ismailsunni** [comment]
Done in #4857
